module.exports = db => {
    const funds = [
      {
         "name":"Cash Reserves Federal Money Market  Admiral Shares",
         "ticker":"VMRXX",
         "assetClass":"Money Market",
         "expenseRatio":"0.10%",
         "price":"$1.00",
         "priceChange":"$0.00",
         "ytd":"0.01%",
         "oneyr":"0.01%",
         "fiveyr":"1.20%",
         "tenyr":"0.68%",
         "sinceInception":"2.94%"
      },
      {
         "name":"Federal Money Market",
         "ticker":"VMFXX",
         "assetClass":"Money Market",
         "expenseRatio":"0.11%",
         "price":"$1.00",
         "priceChange":"$0.00",
         "ytd":"0.01%",
         "oneyr":"0.01%",
         "fiveyr":"1.04%",
         "tenyr":"0.55%",
         "sinceInception":"3.95%"
      },
      {
         "name":"Treasury Money Market",
         "ticker":"VUSXX",
         "assetClass":"Money Market",
         "expenseRatio":"0.09%",
         "price":"$1.00",
         "priceChange":"$0.00",
         "ytd":"0.01%",
         "oneyr":"0.02%",
         "fiveyr":"1.04%",
         "tenyr":"0.55%",
         "sinceInception":"2.31%"
      },
      {
         "name":"California Municipal Money Market",
         "ticker":"VCTXX",
         "assetClass":"Money Market",
         "expenseRatio":"0.16%",
         "price":"$1.00",
         "priceChange":"$0.00",
         "ytd":"0.01%",
         "oneyr":"0.01%",
         "fiveyr":"0.72%",
         "tenyr":"0.39%",
         "sinceInception":"2.09%"
      },
      {
         "name":"Municipal Money Market",
         "ticker":"VMSXX",
         "assetClass":"Money Market",
         "expenseRatio":"0.15%",
         "price":"$1.00",
         "priceChange":"$0.00",
         "ytd":"0.01%",
         "oneyr":"0.01%",
         "fiveyr":"0.80%",
         "tenyr":"0.44%",
         "sinceInception":"2.76%"
      },
      {
         "name":"New York Municipal Money Market",
         "ticker":"VYFXX",
         "assetClass":"Money Market",
         "expenseRatio":"0.16%",
         "price":"$1.00",
         "priceChange":"$0.00",
         "ytd":"0.01%",
         "oneyr":"0.01%",
         "fiveyr":"0.77%",
         "tenyr":"0.42%",
         "sinceInception":"1.36%"
      },
      {
         "name":"GNMA",
         "ticker":"VFIIX",
         "assetClass":"Bond - Inter-term Government",
         "expenseRatio":"0.21%",
         "price":"$10.56",
         "priceChange":"-$0.01",
         "ytd":"-0.96%",
         "oneyr":"-0.40%",
         "fiveyr":"2.27%",
         "tenyr":"2.17%",
         "sinceInception":"6.77%"
      },
      {
         "name":"Inflation-Protected Securities",
         "ticker":"VIPSX",
         "assetClass":"Bond - Inter-term Government",
         "expenseRatio":"0.20%",
         "price":"$14.66",
         "priceChange":"$0.00",
         "ytd":"4.69%",
         "oneyr":"6.59%",
         "fiveyr":"5.02%",
         "tenyr":"2.88%",
         "sinceInception":"5.37%"
      },
      {
         "name":"Intermediate-Term Bond Index  Admiral Shares",
         "ticker":"VBILX",
         "assetClass":"Bond - Inter-term Investment",
         "expenseRatio":"0.07%",
         "price":"$12.07",
         "priceChange":"-$0.01",
         "ytd":"-2.02%",
         "oneyr":"-1.89%",
         "fiveyr":"4.19%",
         "tenyr":"3.70%",
         "sinceInception":"4.95%"
      },
      {
         "name":"Intermediate-Term Treasury",
         "ticker":"VFITX",
         "assetClass":"Bond - Inter-term Government",
         "expenseRatio":"0.20%",
         "price":"$11.36",
         "priceChange":"$0.00",
         "ytd":"-1.89%",
         "oneyr":"-1.81%",
         "fiveyr":"2.95%",
         "tenyr":"2.22%",
         "sinceInception":"5.38%"
      },
      {
         "name":"Intermediate-Term Treasury Index  Admiral Shares",
         "ticker":"VSIGX",
         "assetClass":"Bond - Inter-term Government",
         "expenseRatio":"0.07%",
         "price":"$22.71",
         "priceChange":"$0.01",
         "ytd":"-2.14%",
         "oneyr":"-2.24%",
         "fiveyr":"2.84%",
         "tenyr":"2.19%",
         "sinceInception":"2.64%"
      },
      {
         "name":"Long-Term Bond Index  Admiral Shares",
         "ticker":"VBLAX",
         "assetClass":"Bond - Long-term Investment",
         "expenseRatio":"0.07%",
         "price":"$15.76",
         "priceChange":"-$0.11",
         "ytd":"-2.38%",
         "oneyr":"-2.16%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"10.55%"
      },
      {
         "name":"Long-Term Treasury",
         "ticker":"VUSTX",
         "assetClass":"Bond - Long-term Government",
         "expenseRatio":"0.20%",
         "price":"$12.92",
         "priceChange":"-$0.08",
         "ytd":"-3.74%",
         "oneyr":"-3.79%",
         "fiveyr":"6.84%",
         "tenyr":"4.93%",
         "sinceInception":"7.54%"
      },
      {
         "name":"Long-Term Treasury Index  Admiral Shares",
         "ticker":"VLGSX",
         "assetClass":"Bond - Long-term Government",
         "expenseRatio":"0.07%",
         "price":"$30.42",
         "priceChange":"-$0.18",
         "ytd":"-4.09%",
         "oneyr":"-4.32%",
         "fiveyr":"6.75%",
         "tenyr":"4.92%",
         "sinceInception":"6.77%"
      },
      {
         "name":"Mortgage-Backed Securities Index  Admiral Shares",
         "ticker":"VMBSX",
         "assetClass":"Bond - Inter-term Government",
         "expenseRatio":"0.07%",
         "price":"$21.16",
         "priceChange":"-$0.01",
         "ytd":"-1.26%",
         "oneyr":"-0.87%",
         "fiveyr":"2.37%",
         "tenyr":"2.22%",
         "sinceInception":"2.65%"
      },
      {
         "name":"Short-Term Bond Index  Admiral Shares",
         "ticker":"VBIRX",
         "assetClass":"Bond - Short-term Investment",
         "expenseRatio":"0.07%",
         "price":"$10.65",
         "priceChange":"$0.00",
         "ytd":"-0.92%",
         "oneyr":"-0.76%",
         "fiveyr":"2.23%",
         "tenyr":"1.73%",
         "sinceInception":"2.83%"
      },
      {
         "name":"Short-Term Federal",
         "ticker":"VSGBX",
         "assetClass":"Bond - Short-term Government",
         "expenseRatio":"0.20%",
         "price":"$10.86",
         "priceChange":"$0.00",
         "ytd":"-0.53%",
         "oneyr":"-0.13%",
         "fiveyr":"1.98%",
         "tenyr":"1.43%",
         "sinceInception":"4.53%"
      },
      {
         "name":"Short-Term Inflation-Protected Securities Index  Admiral Shares",
         "ticker":"VTAPX",
         "assetClass":"Bond - Short-term Government",
         "expenseRatio":"0.06%",
         "price":"$26.11",
         "priceChange":"$0.01",
         "ytd":"4.81%",
         "oneyr":"5.91%",
         "fiveyr":"3.26%",
         "tenyr":"—",
         "sinceInception":"1.77%"
      },
      {
         "name":"Short-Term Treasury",
         "ticker":"VFISX",
         "assetClass":"Bond - Short-term Government",
         "expenseRatio":"0.20%",
         "price":"$10.63",
         "priceChange":"$0.00",
         "ytd":"-0.79%",
         "oneyr":"-0.56%",
         "fiveyr":"1.71%",
         "tenyr":"1.15%",
         "sinceInception":"3.73%"
      },
      {
         "name":"Short-Term Treasury Index  Admiral Shares",
         "ticker":"VSBSX",
         "assetClass":"Bond - Short-term Government",
         "expenseRatio":"0.07%",
         "price":"$20.37",
         "priceChange":"$0.00",
         "ytd":"-0.58%",
         "oneyr":"-0.37%",
         "fiveyr":"1.60%",
         "tenyr":"1.05%",
         "sinceInception":"1.18%"
      },
      {
         "name":"Total Bond Market Index  Admiral Shares",
         "ticker":"VBTLX",
         "assetClass":"Bond - Inter-term Investment",
         "expenseRatio":"0.05%",
         "price":"$11.23",
         "priceChange":"-$0.02",
         "ytd":"-1.52%",
         "oneyr":"-1.12%",
         "fiveyr":"3.71%",
         "tenyr":"3.01%",
         "sinceInception":"4.12%"
      },
      {
         "name":"Core Bond",
         "ticker":"VCORX",
         "assetClass":"Bond - Inter-term Investment",
         "expenseRatio":"0.25%",
         "price":"$10.65",
         "priceChange":"-$0.02",
         "ytd":"-1.33%",
         "oneyr":"-0.85%",
         "fiveyr":"4.17%",
         "tenyr":"—",
         "sinceInception":"3.70%"
      },
      {
         "name":"Core-Plus Bond",
         "ticker":"VCPIX",
         "assetClass":"Bond - Inter-term Investment",
         "expenseRatio":"0.30%",
         "price":"$10.03",
         "priceChange":"-$0.01",
         "ytd":"—",
         "oneyr":"—",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"0.42%"
      },
      {
         "name":"Intermediate-Term Corporate Bond Index  Admiral Shares",
         "ticker":"VICSX",
         "assetClass":"Bond - Inter-term Investment",
         "expenseRatio":"0.07%",
         "price":"$25.26",
         "priceChange":"-$0.03",
         "ytd":"-1.47%",
         "oneyr":"-1.33%",
         "fiveyr":"4.95%",
         "tenyr":"4.96%",
         "sinceInception":"5.37%"
      },
      {
         "name":"Intermediate-Term Investment-Grade",
         "ticker":"VFICX",
         "assetClass":"Bond - Inter-term Investment",
         "expenseRatio":"0.20%",
         "price":"$10.06",
         "priceChange":"-$0.02",
         "ytd":"-1.21%",
         "oneyr":"-0.92%",
         "fiveyr":"4.46%",
         "tenyr":"4.28%",
         "sinceInception":"5.56%"
      },
      {
         "name":"Long-Term Corporate Bond Index  Admiral Shares",
         "ticker":"VLTCX",
         "assetClass":"Bond - Long-term Investment",
         "expenseRatio":"0.07%",
         "price":"$28.52",
         "priceChange":"-$0.21",
         "ytd":"-1.46%",
         "oneyr":"-1.20%",
         "fiveyr":"7.95%",
         "tenyr":"6.95%",
         "sinceInception":"7.59%"
      },
      {
         "name":"Long-Term Investment-Grade",
         "ticker":"VWESX",
         "assetClass":"Bond - Long-term Investment",
         "expenseRatio":"0.22%",
         "price":"$11.12",
         "priceChange":"-$0.08",
         "ytd":"-2.47%",
         "oneyr":"-1.63%",
         "fiveyr":"7.81%",
         "tenyr":"6.94%",
         "sinceInception":"8.33%"
      },
      {
         "name":"Short-Term Corporate Bond Index  Admiral Shares",
         "ticker":"VSCSX",
         "assetClass":"Bond - Short-term Investment",
         "expenseRatio":"0.07%",
         "price":"$22.19",
         "priceChange":"$0.00",
         "ytd":"-0.50%",
         "oneyr":"-0.13%",
         "fiveyr":"2.94%",
         "tenyr":"2.83%",
         "sinceInception":"2.70%"
      },
      {
         "name":"Short-Term Investment-Grade",
         "ticker":"VFSTX",
         "assetClass":"Bond - Short-term Investment",
         "expenseRatio":"0.20%",
         "price":"$10.81",
         "priceChange":"$0.00",
         "ytd":"-0.47%",
         "oneyr":"-0.12%",
         "fiveyr":"2.64%",
         "tenyr":"2.45%",
         "sinceInception":"5.71%"
      },
      {
         "name":"Ultra-Short-Term Bond",
         "ticker":"VUBFX",
         "assetClass":"Bond - Short-term Investment",
         "expenseRatio":"0.20%",
         "price":"$10.03",
         "priceChange":"$0.00",
         "ytd":"0.08%",
         "oneyr":"0.25%",
         "fiveyr":"1.74%",
         "tenyr":"—",
         "sinceInception":"1.49%"
      },
      {
         "name":"High-Yield Corporate",
         "ticker":"VWEHX",
         "assetClass":"Bond - Inter-term Low Quality",
         "expenseRatio":"0.23%",
         "price":"$5.92",
         "priceChange":"$0.00",
         "ytd":"3.04%",
         "oneyr":"3.18%",
         "fiveyr":"5.53%",
         "tenyr":"6.16%",
         "sinceInception":"8.12%"
      },
      {
         "name":"California Intermediate-Term Tax-Exempt",
         "ticker":"VCAIX",
         "assetClass":"Bond - Inter-term State Muni",
         "expenseRatio":"0.17%",
         "price":"$12.22",
         "priceChange":"$0.01",
         "ytd":"0.80%",
         "oneyr":"1.13%",
         "fiveyr":"3.85%",
         "tenyr":"3.66%",
         "sinceInception":"4.58%"
      },
      {
         "name":"California Long-Term Tax-Exempt",
         "ticker":"VCITX",
         "assetClass":"Bond - Long-term State Muni",
         "expenseRatio":"0.17%",
         "price":"$12.76",
         "priceChange":"$0.00",
         "ytd":"1.87%",
         "oneyr":"2.22%",
         "fiveyr":"4.96%",
         "tenyr":"4.73%",
         "sinceInception":"5.80%"
      },
      {
         "name":"High-Yield Tax-Exempt",
         "ticker":"VWAHX",
         "assetClass":"Bond - Long-term National Muni",
         "expenseRatio":"0.17%",
         "price":"$12.08",
         "priceChange":"$0.00",
         "ytd":"3.82%",
         "oneyr":"4.96%",
         "fiveyr":"5.66%",
         "tenyr":"5.12%",
         "sinceInception":"6.43%"
      },
      {
         "name":"Intermediate-Term Tax-Exempt",
         "ticker":"VWITX",
         "assetClass":"Bond - Inter-term National Muni",
         "expenseRatio":"0.17%",
         "price":"$14.72",
         "priceChange":"$0.00",
         "ytd":"1.06%",
         "oneyr":"1.62%",
         "fiveyr":"3.92%",
         "tenyr":"3.47%",
         "sinceInception":"5.24%"
      },
      {
         "name":"Limited-Term Tax-Exempt",
         "ticker":"VMLTX",
         "assetClass":"Bond - Short-term National Muni",
         "expenseRatio":"0.17%",
         "price":"$11.17",
         "priceChange":"$0.00",
         "ytd":"0.37%",
         "oneyr":"0.70%",
         "fiveyr":"2.30%",
         "tenyr":"1.71%",
         "sinceInception":"3.84%"
      },
      {
         "name":"Long-Term Tax-Exempt",
         "ticker":"VWLTX",
         "assetClass":"Bond - Long-term National Muni",
         "expenseRatio":"0.17%",
         "price":"$12.19",
         "priceChange":"$0.00",
         "ytd":"2.15%",
         "oneyr":"2.97%",
         "fiveyr":"5.07%",
         "tenyr":"4.61%",
         "sinceInception":"5.77%"
      },
      {
         "name":"Massachusetts Tax-Exempt",
         "ticker":"VMATX",
         "assetClass":"Bond - Long-term State Muni",
         "expenseRatio":"0.13%",
         "price":"$11.41",
         "priceChange":"$0.00",
         "ytd":"1.94%",
         "oneyr":"2.52%",
         "fiveyr":"4.94%",
         "tenyr":"4.20%",
         "sinceInception":"4.47%"
      },
      {
         "name":"New Jersey Long-Term Tax-Exempt",
         "ticker":"VNJTX",
         "assetClass":"Bond - Long-term State Muni",
         "expenseRatio":"0.17%",
         "price":"$12.75",
         "priceChange":"$0.00",
         "ytd":"3.03%",
         "oneyr":"4.26%",
         "fiveyr":"5.73%",
         "tenyr":"4.72%",
         "sinceInception":"5.80%"
      },
      {
         "name":"New York Long-Term Tax-Exempt",
         "ticker":"VNYTX",
         "assetClass":"Bond - Long-term State Muni",
         "expenseRatio":"0.17%",
         "price":"$12.21",
         "priceChange":"$0.00",
         "ytd":"2.44%",
         "oneyr":"3.34%",
         "fiveyr":"4.70%",
         "tenyr":"4.30%",
         "sinceInception":"5.56%"
      },
      {
         "name":"Ohio Long-Term Tax-Exempt",
         "ticker":"VOHIX",
         "assetClass":"Bond - Long-term State Muni",
         "expenseRatio":"0.13%",
         "price":"$13.22",
         "priceChange":"$0.01",
         "ytd":"2.13%",
         "oneyr":"2.59%",
         "fiveyr":"5.13%",
         "tenyr":"4.62%",
         "sinceInception":"5.70%"
      },
      {
         "name":"Pennsylvania Long-Term Tax-Exempt",
         "ticker":"VPAIX",
         "assetClass":"Bond - Long-term State Muni",
         "expenseRatio":"0.17%",
         "price":"$12.13",
         "priceChange":"$0.00",
         "ytd":"2.35%",
         "oneyr":"2.99%",
         "fiveyr":"5.18%",
         "tenyr":"4.54%",
         "sinceInception":"5.78%"
      },
      {
         "name":"Short-Term Tax-Exempt",
         "ticker":"VWSTX",
         "assetClass":"Bond - Short-term National Muni",
         "expenseRatio":"0.17%",
         "price":"$15.88",
         "priceChange":"$0.00",
         "ytd":"0.16%",
         "oneyr":"0.32%",
         "fiveyr":"1.42%",
         "tenyr":"1.01%",
         "sinceInception":"3.66%"
      },
      {
         "name":"Tax-Exempt Bond Index  Admiral Shares",
         "ticker":"VTEAX",
         "assetClass":"Bond - Inter-term National Muni",
         "expenseRatio":"0.09%",
         "price":"$22.00",
         "priceChange":"$0.01",
         "ytd":"1.40%",
         "oneyr":"1.92%",
         "fiveyr":"4.13%",
         "tenyr":"—",
         "sinceInception":"3.53%"
      },
      {
         "name":"Target Retirement 2015",
         "ticker":"VTXVX",
         "assetClass":"Balanced",
         "expenseRatio":"0.12%",
         "price":"$16.45",
         "priceChange":"-$0.07",
         "ytd":"4.58%",
         "oneyr":"6.72%",
         "fiveyr":"7.71%",
         "tenyr":"7.39%",
         "sinceInception":"6.42%"
      },
      {
         "name":"Target Retirement 2020",
         "ticker":"VTWNX",
         "assetClass":"Balanced",
         "expenseRatio":"0.13%",
         "price":"$36.47",
         "priceChange":"-$0.20",
         "ytd":"6.36%",
         "oneyr":"9.25%",
         "fiveyr":"9.19%",
         "tenyr":"8.57%",
         "sinceInception":"6.86%"
      },
      {
         "name":"Target Retirement 2025",
         "ticker":"VTTVX",
         "assetClass":"Balanced",
         "expenseRatio":"0.13%",
         "price":"$23.15",
         "priceChange":"-$0.15",
         "ytd":"7.47%",
         "oneyr":"10.86%",
         "fiveyr":"10.21%",
         "tenyr":"9.40%",
         "sinceInception":"7.39%"
      },
      {
         "name":"Target Retirement 2030",
         "ticker":"VTHRX",
         "assetClass":"Balanced",
         "expenseRatio":"0.14%",
         "price":"$44.04",
         "priceChange":"-$0.34",
         "ytd":"8.61%",
         "oneyr":"12.49%",
         "fiveyr":"11.03%",
         "tenyr":"10.11%",
         "sinceInception":"7.52%"
      },
      {
         "name":"Target Retirement 2035",
         "ticker":"VTTHX",
         "assetClass":"Balanced",
         "expenseRatio":"0.14%",
         "price":"$27.69",
         "priceChange":"-$0.23",
         "ytd":"9.79%",
         "oneyr":"14.11%",
         "fiveyr":"11.81%",
         "tenyr":"10.80%",
         "sinceInception":"8.18%"
      },
      {
         "name":"Target Retirement 2040",
         "ticker":"VFORX",
         "assetClass":"Balanced",
         "expenseRatio":"0.14%",
         "price":"$49.12",
         "priceChange":"-$0.45",
         "ytd":"10.96%",
         "oneyr":"15.76%",
         "fiveyr":"12.60%",
         "tenyr":"11.34%",
         "sinceInception":"8.15%"
      },
      {
         "name":"Target Retirement 2045",
         "ticker":"VTIVX",
         "assetClass":"Balanced",
         "expenseRatio":"0.15%",
         "price":"$31.61",
         "priceChange":"-$0.31",
         "ytd":"12.13%",
         "oneyr":"17.39%",
         "fiveyr":"13.19%",
         "tenyr":"11.65%",
         "sinceInception":"8.81%"
      },
      {
         "name":"Target Retirement 2050",
         "ticker":"VFIFX",
         "assetClass":"Balanced",
         "expenseRatio":"0.15%",
         "price":"$51.04",
         "priceChange":"-$0.50",
         "ytd":"12.30%",
         "oneyr":"17.60%",
         "fiveyr":"13.24%",
         "tenyr":"11.67%",
         "sinceInception":"8.39%"
      },
      {
         "name":"Target Retirement 2055",
         "ticker":"VFFVX",
         "assetClass":"Balanced",
         "expenseRatio":"0.15%",
         "price":"$55.41",
         "priceChange":"-$0.55",
         "ytd":"12.30%",
         "oneyr":"17.60%",
         "fiveyr":"13.24%",
         "tenyr":"11.66%",
         "sinceInception":"11.42%"
      },
      {
         "name":"Target Retirement 2060",
         "ticker":"VTTSX",
         "assetClass":"Balanced",
         "expenseRatio":"0.15%",
         "price":"$48.96",
         "priceChange":"-$0.48",
         "ytd":"12.32%",
         "oneyr":"17.61%",
         "fiveyr":"13.24%",
         "tenyr":"—",
         "sinceInception":"11.34%"
      },
      {
         "name":"Target Retirement 2065",
         "ticker":"VLXVX",
         "assetClass":"Balanced",
         "expenseRatio":"0.15%",
         "price":"$30.89",
         "priceChange":"-$0.30",
         "ytd":"12.33%",
         "oneyr":"17.59%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"12.01%"
      },
      {
         "name":"Target Retirement Income",
         "ticker":"VTINX",
         "assetClass":"Balanced",
         "expenseRatio":"0.12%",
         "price":"$15.38",
         "priceChange":"-$0.06",
         "ytd":"4.12%",
         "oneyr":"6.05%",
         "fiveyr":"6.83%",
         "tenyr":"5.83%",
         "sinceInception":"5.59%"
      },
      {
         "name":"LifeStrategy Conservative Growth",
         "ticker":"VSCGX",
         "assetClass":"Balanced",
         "expenseRatio":"0.12%",
         "price":"$23.47",
         "priceChange":"-$0.12",
         "ytd":"4.62%",
         "oneyr":"6.94%",
         "fiveyr":"7.98%",
         "tenyr":"7.02%",
         "sinceInception":"7.04%"
      },
      {
         "name":"LifeStrategy Growth",
         "ticker":"VASGX",
         "assetClass":"Balanced",
         "expenseRatio":"0.14%",
         "price":"$44.27",
         "priceChange":"-$0.40",
         "ytd":"10.76%",
         "oneyr":"15.46%",
         "fiveyr":"12.22%",
         "tenyr":"10.79%",
         "sinceInception":"8.57%"
      },
      {
         "name":"LifeStrategy Income",
         "ticker":"VASIX",
         "assetClass":"Balanced",
         "expenseRatio":"0.11%",
         "price":"$17.38",
         "priceChange":"-$0.05",
         "ytd":"1.52%",
         "oneyr":"2.80%",
         "fiveyr":"5.76%",
         "tenyr":"5.04%",
         "sinceInception":"6.19%"
      },
      {
         "name":"LifeStrategy Moderate Growth",
         "ticker":"VSMGX",
         "assetClass":"Balanced",
         "expenseRatio":"0.13%",
         "price":"$33.83",
         "priceChange":"-$0.24",
         "ytd":"7.61%",
         "oneyr":"11.10%",
         "fiveyr":"10.11%",
         "tenyr":"8.93%",
         "sinceInception":"7.93%"
      },
      {
         "name":"Balanced Index  Admiral Shares",
         "ticker":"VBIAX",
         "assetClass":"Balanced",
         "expenseRatio":"0.07%",
         "price":"$48.64",
         "priceChange":"-$0.39",
         "ytd":"11.33%",
         "oneyr":"14.84%",
         "fiveyr":"12.15%",
         "tenyr":"10.85%",
         "sinceInception":"7.26%"
      },
      {
         "name":"Managed Allocation",
         "ticker":"VPGDX",
         "assetClass":"Balanced",
         "expenseRatio":"0.28%",
         "price":"$18.95",
         "priceChange":"-$0.14",
         "ytd":"10.59%",
         "oneyr":"13.66%",
         "fiveyr":"8.04%",
         "tenyr":"7.78%",
         "sinceInception":"5.71%"
      },
      {
         "name":"STAR",
         "ticker":"VGSTX",
         "assetClass":"Balanced",
         "expenseRatio":"0.31%",
         "price":"$33.03",
         "priceChange":"-$0.30",
         "ytd":"6.72%",
         "oneyr":"12.09%",
         "fiveyr":"12.65%",
         "tenyr":"10.67%",
         "sinceInception":"9.78%"
      },
      {
         "name":"Tax-Managed Balanced  Admiral Shares",
         "ticker":"VTMFX",
         "assetClass":"Balanced",
         "expenseRatio":"0.09%",
         "price":"$41.68",
         "priceChange":"-$0.23",
         "ytd":"10.74%",
         "oneyr":"13.51%",
         "fiveyr":"10.80%",
         "tenyr":"9.67%",
         "sinceInception":"8.00%"
      },
      {
         "name":"Wellesley Income",
         "ticker":"VWINX",
         "assetClass":"Balanced",
         "expenseRatio":"0.23%",
         "price":"$28.57",
         "priceChange":"-$1.34",
         "ytd":"7.08%",
         "oneyr":"7.36%",
         "fiveyr":"7.83%",
         "tenyr":"7.68%",
         "sinceInception":"9.64%"
      },
      {
         "name":"Wellington",
         "ticker":"VWELX",
         "assetClass":"Balanced",
         "expenseRatio":"0.24%",
         "price":"$50.74",
         "priceChange":"-$0.38",
         "ytd":"15.99%",
         "oneyr":"17.16%",
         "fiveyr":"11.94%",
         "tenyr":"11.14%",
         "sinceInception":"8.43%"
      },
      {
         "name":"Global Wellesley Income",
         "ticker":"VGWIX",
         "assetClass":"Balanced",
         "expenseRatio":"0.41%",
         "price":"$21.86",
         "priceChange":"-$0.06",
         "ytd":"5.26%",
         "oneyr":"5.72%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"4.68%"
      },
      {
         "name":"Global Wellington",
         "ticker":"VGWLX",
         "assetClass":"Balanced",
         "expenseRatio":"0.42%",
         "price":"$25.59",
         "priceChange":"-$0.14",
         "ytd":"10.87%",
         "oneyr":"11.72%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"8.29%"
      },
      {
         "name":"500 Index  Admiral Shares",
         "ticker":"VFIAX",
         "assetClass":"Stock - Large-Cap Blend",
         "expenseRatio":"0.04%",
         "price":"$421.39",
         "priceChange":"-$6.41",
         "ytd":"23.27%",
         "oneyr":"27.89%",
         "fiveyr":"17.86%",
         "tenyr":"16.12%",
         "sinceInception":"8.01%"
      },
      {
         "name":"Diversified Equity",
         "ticker":"VDEQX",
         "assetClass":"Stock - Large-Cap Blend",
         "expenseRatio":"0.35%",
         "price":"$53.89",
         "priceChange":"-$0.77",
         "ytd":"16.34%",
         "oneyr":"24.86%",
         "fiveyr":"18.77%",
         "tenyr":"16.26%",
         "sinceInception":"10.68%"
      },
      {
         "name":"Dividend Appreciation Index  Admiral Shares",
         "ticker":"VDADX",
         "assetClass":"Stock - Large-Cap Blend",
         "expenseRatio":"0.08%",
         "price":"$44.69",
         "priceChange":"-$0.49",
         "ytd":"18.55%",
         "oneyr":"19.03%",
         "fiveyr":"16.02%",
         "tenyr":"—",
         "sinceInception":"12.58%"
      },
      {
         "name":"Dividend Growth",
         "ticker":"VDIGX",
         "assetClass":"Stock - Large-Cap Blend",
         "expenseRatio":"0.26%",
         "price":"$39.37",
         "priceChange":"-$0.39",
         "ytd":"19.96%",
         "oneyr":"18.77%",
         "fiveyr":"15.54%",
         "tenyr":"14.01%",
         "sinceInception":"9.33%"
      },
      {
         "name":"Equity Income",
         "ticker":"VEIPX",
         "assetClass":"Stock - Large-Cap Value",
         "expenseRatio":"0.28%",
         "price":"$42.48",
         "priceChange":"-$0.36",
         "ytd":"21.18%",
         "oneyr":"21.56%",
         "fiveyr":"11.75%",
         "tenyr":"12.75%",
         "sinceInception":"10.34%"
      },
      {
         "name":"FTSE Social Index  Admiral Shares",
         "ticker":"VFTAX",
         "assetClass":"Stock - Large-Cap Growth",
         "expenseRatio":"0.14%",
         "price":"$44.53",
         "priceChange":"-$0.53",
         "ytd":"22.43%",
         "oneyr":"28.25%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"24.83%"
      },
      {
         "name":"Growth and Income",
         "ticker":"VQNPX",
         "assetClass":"Stock - Large-Cap Blend",
         "expenseRatio":"0.32%",
         "price":"$61.13",
         "priceChange":"-$10.23",
         "ytd":"23.39%",
         "oneyr":"28.53%",
         "fiveyr":"17.15%",
         "tenyr":"16.06%",
         "sinceInception":"10.92%"
      },
      {
         "name":"Growth Index  Admiral Shares",
         "ticker":"VIGAX",
         "assetClass":"Stock - Large-Cap Growth",
         "expenseRatio":"0.05%",
         "price":"$157.98",
         "priceChange":"-$1.99",
         "ytd":"21.56%",
         "oneyr":"30.34%",
         "fiveyr":"24.61%",
         "tenyr":"19.01%",
         "sinceInception":"9.06%"
      },
      {
         "name":"High Dividend Yield Index  Admiral Shares",
         "ticker":"VHYAX",
         "assetClass":"Stock - Large-Cap Value",
         "expenseRatio":"0.08%",
         "price":"$32.60",
         "priceChange":"-$0.26",
         "ytd":"21.65%",
         "oneyr":"22.23%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"12.56%"
      },
      {
         "name":"Large-Cap Index  Admiral Shares",
         "ticker":"VLCAX",
         "assetClass":"Stock - Large-Cap Blend",
         "expenseRatio":"0.05%",
         "price":"$107.11",
         "priceChange":"-$1.25",
         "ytd":"21.78%",
         "oneyr":"27.04%",
         "fiveyr":"18.22%",
         "tenyr":"16.24%",
         "sinceInception":"10.58%"
      },
      {
         "name":"PRIMECAP",
         "ticker":"VPMCX",
         "assetClass":"Stock - Large-Cap Growth",
         "expenseRatio":"0.38%",
         "price":"$155.87",
         "priceChange":"-$18.87",
         "ytd":"16.08%",
         "oneyr":"24.16%",
         "fiveyr":"17.94%",
         "tenyr":"17.11%",
         "sinceInception":"13.98%"
      },
      {
         "name":"PRIMECAP  Admiral Shares",
         "ticker":"VPMAX",
         "assetClass":"Stock - Large-Cap Growth",
         "expenseRatio":"0.31%",
         "price":"$161.47",
         "priceChange":"-$19.72",
         "ytd":"16.16%",
         "oneyr":"24.24%",
         "fiveyr":"18.02%",
         "tenyr":"17.20%",
         "sinceInception":"11.58%"
      },
      {
         "name":"PRIMECAP Core",
         "ticker":"VPCCX",
         "assetClass":"Stock - Large-Cap Blend",
         "expenseRatio":"0.46%",
         "price":"$32.13",
         "priceChange":"-$2.78",
         "ytd":"18.87%",
         "oneyr":"24.53%",
         "fiveyr":"15.88%",
         "tenyr":"15.78%",
         "sinceInception":"11.55%"
      },
      {
         "name":"Tax-Managed Capital Appreciation  Admiral Shares",
         "ticker":"VTCLX",
         "assetClass":"Stock - Large-Cap Blend",
         "expenseRatio":"0.09%",
         "price":"$238.04",
         "priceChange":"-$2.87",
         "ytd":"21.46%",
         "oneyr":"26.96%",
         "fiveyr":"18.10%",
         "tenyr":"16.29%",
         "sinceInception":"10.91%"
      },
      {
         "name":"Total Stock Market Index  Admiral Shares",
         "ticker":"VTSAX",
         "assetClass":"Stock - Large-Cap Blend",
         "expenseRatio":"0.04%",
         "price":"$112.96",
         "priceChange":"-$1.40",
         "ytd":"20.37%",
         "oneyr":"26.49%",
         "fiveyr":"17.55%",
         "tenyr":"15.95%",
         "sinceInception":"8.45%"
      },
      {
         "name":"U.S. Growth",
         "ticker":"VWUSX",
         "assetClass":"Stock - Large-Cap Growth",
         "expenseRatio":"0.38%",
         "price":"$62.39",
         "priceChange":"-$1.06",
         "ytd":"7.78%",
         "oneyr":"21.08%",
         "fiveyr":"26.44%",
         "tenyr":"20.11%",
         "sinceInception":"11.35%"
      },
      {
         "name":"Value Index  Admiral Shares",
         "ticker":"VVIAX",
         "assetClass":"Stock - Large-Cap Value",
         "expenseRatio":"0.05%",
         "price":"$55.62",
         "priceChange":"-$0.58",
         "ytd":"21.86%",
         "oneyr":"22.59%",
         "fiveyr":"11.60%",
         "tenyr":"13.25%",
         "sinceInception":"7.23%"
      },
      {
         "name":"Windsor",
         "ticker":"VWNDX",
         "assetClass":"Stock - Large-Cap Value",
         "expenseRatio":"0.29%",
         "price":"$23.06",
         "priceChange":"-$2.92",
         "ytd":"22.01%",
         "oneyr":"25.85%",
         "fiveyr":"12.30%",
         "tenyr":"13.46%",
         "sinceInception":"11.39%"
      },
      {
         "name":"Windsor II",
         "ticker":"VWNFX",
         "assetClass":"Stock - Large-Cap Value",
         "expenseRatio":"0.34%",
         "price":"$44.24",
         "priceChange":"-$3.94",
         "ytd":"23.63%",
         "oneyr":"28.58%",
         "fiveyr":"14.49%",
         "tenyr":"13.85%",
         "sinceInception":"11.16%"
      },
      {
         "name":"Capital Opportunity",
         "ticker":"VHCOX",
         "assetClass":"Stock - Mid-Cap Growth",
         "expenseRatio":"0.44%",
         "price":"$80.18",
         "priceChange":"-$9.99",
         "ytd":"15.67%",
         "oneyr":"24.92%",
         "fiveyr":"18.74%",
         "tenyr":"18.08%",
         "sinceInception":"13.20%"
      },
      {
         "name":"Capital Opportunity  Admiral Shares",
         "ticker":"VHCAX",
         "assetClass":"Stock - Mid-Cap Growth",
         "expenseRatio":"0.37%",
         "price":"$185.04",
         "priceChange":"-$23.27",
         "ytd":"15.75%",
         "oneyr":"25.00%",
         "fiveyr":"18.83%",
         "tenyr":"18.16%",
         "sinceInception":"12.25%"
      },
      {
         "name":"Extended Market Index  Admiral Shares",
         "ticker":"VEXAX",
         "assetClass":"Stock - Mid-Cap Blend",
         "expenseRatio":"0.06%",
         "price":"$133.10",
         "priceChange":"-$2.25",
         "ytd":"7.47%",
         "oneyr":"19.90%",
         "fiveyr":"15.59%",
         "tenyr":"14.90%",
         "sinceInception":"9.46%"
      },
      {
         "name":"Mid-Cap Growth",
         "ticker":"VMGRX",
         "assetClass":"Stock - Mid-Cap Growth",
         "expenseRatio":"0.34%",
         "price":"$25.60",
         "priceChange":"-$9.82",
         "ytd":"4.12%",
         "oneyr":"14.49%",
         "fiveyr":"17.56%",
         "tenyr":"14.30%",
         "sinceInception":"11.20%"
      },
      {
         "name":"Mid-Cap Growth Index  Admiral Shares",
         "ticker":"VMGMX",
         "assetClass":"Stock - Mid-Cap Growth",
         "expenseRatio":"0.07%",
         "price":"$104.55",
         "priceChange":"-$1.43",
         "ytd":"14.82%",
         "oneyr":"23.70%",
         "fiveyr":"19.65%",
         "tenyr":"16.01%",
         "sinceInception":"16.27%"
      },
      {
         "name":"Mid-Cap Index  Admiral Shares",
         "ticker":"VIMAX",
         "assetClass":"Stock - Mid-Cap Blend",
         "expenseRatio":"0.05%",
         "price":"$301.67",
         "priceChange":"-$4.37",
         "ytd":"18.64%",
         "oneyr":"24.78%",
         "fiveyr":"15.13%",
         "tenyr":"14.64%",
         "sinceInception":"11.02%"
      },
      {
         "name":"Mid-Cap Value Index  Admiral Shares",
         "ticker":"VMVAX",
         "assetClass":"Stock - Mid-Cap Value",
         "expenseRatio":"0.07%",
         "price":"$74.58",
         "priceChange":"-$1.15",
         "ytd":"22.65%",
         "oneyr":"25.52%",
         "fiveyr":"10.51%",
         "tenyr":"13.03%",
         "sinceInception":"13.64%"
      },
      {
         "name":"Selected Value",
         "ticker":"VASVX",
         "assetClass":"Stock - Mid-Cap Value",
         "expenseRatio":"0.31%",
         "price":"$28.75",
         "priceChange":"-$3.01",
         "ytd":"19.83%",
         "oneyr":"27.03%",
         "fiveyr":"9.88%",
         "tenyr":"11.89%",
         "sinceInception":"9.09%"
      },
      {
         "name":"Strategic Equity",
         "ticker":"VSEQX",
         "assetClass":"Stock - Mid-Cap Blend",
         "expenseRatio":"0.17%",
         "price":"$36.52",
         "priceChange":"-$0.64",
         "ytd":"23.26%",
         "oneyr":"32.16%",
         "fiveyr":"12.25%",
         "tenyr":"14.41%",
         "sinceInception":"11.01%"
      },
      {
         "name":"Explorer",
         "ticker":"VEXPX",
         "assetClass":"Stock - Small-Cap Growth",
         "expenseRatio":"0.41%",
         "price":"$121.65",
         "priceChange":"-$22.68",
         "ytd":"10.44%",
         "oneyr":"23.18%",
         "fiveyr":"18.84%",
         "tenyr":"15.77%",
         "sinceInception":"9.94%"
      },
      {
         "name":"Explorer Value",
         "ticker":"VEVFX",
         "assetClass":"Stock - Small-Cap Value",
         "expenseRatio":"0.52%",
         "price":"$43.34",
         "priceChange":"-$0.87",
         "ytd":"20.38%",
         "oneyr":"31.93%",
         "fiveyr":"9.93%",
         "tenyr":"12.30%",
         "sinceInception":"11.62%"
      },
      {
         "name":"Small-Cap Growth Index  Admiral Shares",
         "ticker":"VSGAX",
         "assetClass":"Stock - Small-Cap Growth",
         "expenseRatio":"0.07%",
         "price":"$94.60",
         "priceChange":"-$1.42",
         "ytd":"0.85%",
         "oneyr":"12.63%",
         "fiveyr":"16.67%",
         "tenyr":"14.58%",
         "sinceInception":"15.24%"
      },
      {
         "name":"Small-Cap Index  Admiral Shares",
         "ticker":"VSMAX",
         "assetClass":"Stock - Small-Cap Blend",
         "expenseRatio":"0.05%",
         "price":"$103.19",
         "priceChange":"-$1.83",
         "ytd":"11.56%",
         "oneyr":"22.18%",
         "fiveyr":"13.13%",
         "tenyr":"13.79%",
         "sinceInception":"9.91%"
      },
      {
         "name":"Small-Cap Value Index  Admiral Shares",
         "ticker":"VSIAX",
         "assetClass":"Stock - Small-Cap Value",
         "expenseRatio":"0.07%",
         "price":"$72.91",
         "priceChange":"-$1.44",
         "ytd":"20.78%",
         "oneyr":"30.27%",
         "fiveyr":"9.87%",
         "tenyr":"12.87%",
         "sinceInception":"13.59%"
      },
      {
         "name":"Strategic Small-Cap Equity",
         "ticker":"VSTCX",
         "assetClass":"Stock - Small-Cap Blend",
         "expenseRatio":"0.26%",
         "price":"$36.76",
         "priceChange":"-$0.64",
         "ytd":"25.65%",
         "oneyr":"36.80%",
         "fiveyr":"11.03%",
         "tenyr":"13.33%",
         "sinceInception":"8.41%"
      },
      {
         "name":"Tax-Managed Small-Cap  Admiral Shares",
         "ticker":"VTMSX",
         "assetClass":"Stock - Small-Cap Blend",
         "expenseRatio":"0.09%",
         "price":"$88.46",
         "priceChange":"-$1.36",
         "ytd":"20.00%",
         "oneyr":"31.46%",
         "fiveyr":"12.17%",
         "tenyr":"14.08%",
         "sinceInception":"11.19%"
      },
      {
         "name":"Global Credit Bond",
         "ticker":"VGCIX",
         "assetClass":"International",
         "expenseRatio":"0.35%",
         "price":"$11.05",
         "priceChange":"-$0.02",
         "ytd":"-0.52%",
         "oneyr":"0.12%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"7.73%"
      },
      {
         "name":"Total International Bond Index  Admiral Shares",
         "ticker":"VTABX",
         "assetClass":"International",
         "expenseRatio":"0.11%",
         "price":"$22.93",
         "priceChange":"-$0.01",
         "ytd":"-1.24%",
         "oneyr":"-1.15%",
         "fiveyr":"3.30%",
         "tenyr":"—",
         "sinceInception":"3.56%"
      },
      {
         "name":"Emerging Markets Bond",
         "ticker":"VEMBX",
         "assetClass":"International",
         "expenseRatio":"0.60%",
         "price":"$11.68",
         "priceChange":"-$0.03",
         "ytd":"-1.66%",
         "oneyr":"-0.56%",
         "fiveyr":"8.43%",
         "tenyr":"—",
         "sinceInception":"8.74%"
      },
      {
         "name":"Emerging Markets Government Bond Index  Admiral Shares",
         "ticker":"VGAVX",
         "assetClass":"International",
         "expenseRatio":"0.25%",
         "price":"$19.36",
         "priceChange":"-$0.09",
         "ytd":"-2.55%",
         "oneyr":"-2.41%",
         "fiveyr":"4.27%",
         "tenyr":"—",
         "sinceInception":"3.94%"
      },
      {
         "name":"Global Capital Cycles",
         "ticker":"VGPMX",
         "assetClass":"International",
         "expenseRatio":"0.35%",
         "price":"$10.90",
         "priceChange":"-$0.08",
         "ytd":"14.16%",
         "oneyr":"24.73%",
         "fiveyr":"4.38%",
         "tenyr":"-5.41%",
         "sinceInception":"4.28%"
      },
      {
         "name":"Global Equity",
         "ticker":"VHGEX",
         "assetClass":"International",
         "expenseRatio":"0.45%",
         "price":"$36.99",
         "priceChange":"-$0.47",
         "ytd":"8.78%",
         "oneyr":"16.53%",
         "fiveyr":"15.45%",
         "tenyr":"12.94%",
         "sinceInception":"9.62%"
      },
      {
         "name":"Global ESG Select Stock",
         "ticker":"VEIGX",
         "assetClass":"International",
         "expenseRatio":"0.55%",
         "price":"$31.15",
         "priceChange":"-$0.18",
         "ytd":"17.47%",
         "oneyr":"18.69%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"19.48%"
      },
      {
         "name":"Total World Stock Index  Admiral Shares",
         "ticker":"VTWAX",
         "assetClass":"International",
         "expenseRatio":"0.10%",
         "price":"$36.55",
         "priceChange":"-$0.40",
         "ytd":"13.47%",
         "oneyr":"19.35%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"17.10%"
      },
      {
         "name":"Developed Markets Index  Admiral Shares",
         "ticker":"VTMGX",
         "assetClass":"International",
         "expenseRatio":"0.07%",
         "price":"$15.85",
         "priceChange":"-$0.09",
         "ytd":"7.43%",
         "oneyr":"12.51%",
         "fiveyr":"9.66%",
         "tenyr":"7.75%",
         "sinceInception":"4.69%"
      },
      {
         "name":"European Stock Index  Admiral Shares",
         "ticker":"VEUSX",
         "assetClass":"International",
         "expenseRatio":"0.10%",
         "price":"$81.74",
         "priceChange":"-$0.07",
         "ytd":"11.13%",
         "oneyr":"15.95%",
         "fiveyr":"10.51%",
         "tenyr":"7.81%",
         "sinceInception":"6.03%"
      },
      {
         "name":"FTSE All-World ex-US Index  Admiral Shares",
         "ticker":"VFWAX",
         "assetClass":"International",
         "expenseRatio":"0.11%",
         "price":"$36.82",
         "priceChange":"-$0.30",
         "ytd":"4.40%",
         "oneyr":"9.82%",
         "fiveyr":"9.47%",
         "tenyr":"6.90%",
         "sinceInception":"7.23%"
      },
      {
         "name":"FTSE All-World ex-US Small-Cap Index  Admiral Shares",
         "ticker":"VFSAX",
         "assetClass":"International",
         "expenseRatio":"0.16%",
         "price":"$31.44",
         "priceChange":"-$0.29",
         "ytd":"7.18%",
         "oneyr":"15.74%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"12.03%"
      },
      {
         "name":"Global ex-U.S. Real Estate Index  Admiral Shares",
         "ticker":"VGRLX",
         "assetClass":"International",
         "expenseRatio":"0.12%",
         "price":"$31.60",
         "priceChange":"-$2.18",
         "ytd":"2.31%",
         "oneyr":"5.96%",
         "fiveyr":"5.82%",
         "tenyr":"6.81%",
         "sinceInception":"5.04%"
      },
      {
         "name":"International Core Stock",
         "ticker":"VWICX",
         "assetClass":"International",
         "expenseRatio":"0.46%",
         "price":"$11.90",
         "priceChange":"-$0.09",
         "ytd":"8.01%",
         "oneyr":"11.98%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"10.51%"
      },
      {
         "name":"International Dividend Appreciation Index  Admiral Shares",
         "ticker":"VIAAX",
         "assetClass":"International",
         "expenseRatio":"0.20%",
         "price":"$40.20",
         "priceChange":"-$0.26",
         "ytd":"8.83%",
         "oneyr":"12.45%",
         "fiveyr":"12.47%",
         "tenyr":"—",
         "sinceInception":"11.15%"
      },
      {
         "name":"International Explorer",
         "ticker":"VINEX",
         "assetClass":"International",
         "expenseRatio":"0.39%",
         "price":"$20.35",
         "priceChange":"-$1.16",
         "ytd":"4.76%",
         "oneyr":"14.16%",
         "fiveyr":"10.08%",
         "tenyr":"9.37%",
         "sinceInception":"9.10%"
      },
      {
         "name":"International Growth",
         "ticker":"VWIGX",
         "assetClass":"International",
         "expenseRatio":"0.43%",
         "price":"$41.97",
         "priceChange":"-$0.53",
         "ytd":"-5.01%",
         "oneyr":"6.96%",
         "fiveyr":"21.39%",
         "tenyr":"13.64%",
         "sinceInception":"11.38%"
      },
      {
         "name":"International High Dividend Yield Index  Admiral Shares",
         "ticker":"VIHAX",
         "assetClass":"International",
         "expenseRatio":"0.28%",
         "price":"$31.52",
         "priceChange":"-$0.19",
         "ytd":"11.49%",
         "oneyr":"14.42%",
         "fiveyr":"7.07%",
         "tenyr":"—",
         "sinceInception":"7.67%"
      },
      {
         "name":"International Value",
         "ticker":"VTRIX",
         "assetClass":"International",
         "expenseRatio":"0.35%",
         "price":"$40.02",
         "priceChange":"-$2.20",
         "ytd":"3.92%",
         "oneyr":"10.50%",
         "fiveyr":"8.45%",
         "tenyr":"6.76%",
         "sinceInception":"8.52%"
      },
      {
         "name":"Pacific Stock Index  Admiral Shares",
         "ticker":"VPADX",
         "assetClass":"International",
         "expenseRatio":"0.10%",
         "price":"$95.10",
         "priceChange":"-$0.97",
         "ytd":"-0.25%",
         "oneyr":"4.47%",
         "fiveyr":"8.19%",
         "tenyr":"7.31%",
         "sinceInception":"5.71%"
      },
      {
         "name":"Total International Stock Index  Admiral Shares",
         "ticker":"VTIAX",
         "assetClass":"International",
         "expenseRatio":"0.11%",
         "price":"$32.98",
         "priceChange":"-$0.28",
         "ytd":"4.75%",
         "oneyr":"10.47%",
         "fiveyr":"9.46%",
         "tenyr":"6.96%",
         "sinceInception":"5.71%"
      },
      {
         "name":"Emerging Markets Select Stock",
         "ticker":"VMMSX",
         "assetClass":"International",
         "expenseRatio":"0.85%",
         "price":"$23.54",
         "priceChange":"-$2.14",
         "ytd":"-4.83%",
         "oneyr":"4.61%",
         "fiveyr":"9.54%",
         "tenyr":"5.63%",
         "sinceInception":"3.86%"
      },
      {
         "name":"Emerging Markets Stock Index  Admiral Shares",
         "ticker":"VEMAX",
         "assetClass":"International",
         "expenseRatio":"0.14%",
         "price":"$39.58",
         "priceChange":"-$0.68",
         "ytd":"-2.63%",
         "oneyr":"5.00%",
         "fiveyr":"9.02%",
         "tenyr":"4.82%",
         "sinceInception":"5.87%"
      },
      {
         "name":"Global Minimum Volatility",
         "ticker":"VMVFX",
         "assetClass":"International",
         "expenseRatio":"0.21%",
         "price":"$14.42",
         "priceChange":"-$0.06",
         "ytd":"9.14%",
         "oneyr":"9.29%",
         "fiveyr":"7.61%",
         "tenyr":"—",
         "sinceInception":"8.49%"
      },
      {
         "name":"Energy",
         "ticker":"VGENX",
         "assetClass":"Stock - Sector",
         "expenseRatio":"0.37%",
         "price":"$38.50",
         "priceChange":"-$0.12",
         "ytd":"22.98%",
         "oneyr":"24.68%",
         "fiveyr":"-3.86%",
         "tenyr":"-1.61%",
         "sinceInception":"8.83%"
      },
      {
         "name":"Health Care",
         "ticker":"VGHCX",
         "assetClass":"Stock - Sector",
         "expenseRatio":"0.32%",
         "price":"$237.55",
         "priceChange":"-$0.54",
         "ytd":"11.85%",
         "oneyr":"8.87%",
         "fiveyr":"12.29%",
         "tenyr":"14.71%",
         "sinceInception":"15.85%"
      },
      {
         "name":"Real Estate Index  Admiral Shares",
         "ticker":"VGSLX",
         "assetClass":"Stock - Sector",
         "expenseRatio":"0.12%",
         "price":"$157.04",
         "priceChange":"-$1.43",
         "ytd":"32.97%",
         "oneyr":"31.52%",
         "fiveyr":"10.20%",
         "tenyr":"10.98%",
         "sinceInception":"10.68%"
      },
      {
         "name":"Cash Reserves Federal Money Market  Admiral Shares",
         "ticker":"VMRXX",
         "assetClass":"Money Market",
         "expenseRatio":"0.10%",
         "price":"$1.00",
         "priceChange":"$0.00",
         "ytd":"0.01%",
         "oneyr":"0.01%",
         "fiveyr":"1.20%",
         "tenyr":"0.68%",
         "sinceInception":"2.94%"
      },
      {
         "name":"Federal Money Market",
         "ticker":"VMFXX",
         "assetClass":"Money Market",
         "expenseRatio":"0.11%",
         "price":"$1.00",
         "priceChange":"$0.00",
         "ytd":"0.01%",
         "oneyr":"0.01%",
         "fiveyr":"1.04%",
         "tenyr":"0.55%",
         "sinceInception":"3.95%"
      },
      {
         "name":"Treasury Money Market",
         "ticker":"VUSXX",
         "assetClass":"Money Market",
         "expenseRatio":"0.09%",
         "price":"$1.00",
         "priceChange":"$0.00",
         "ytd":"0.01%",
         "oneyr":"0.02%",
         "fiveyr":"1.04%",
         "tenyr":"0.55%",
         "sinceInception":"2.31%"
      },
      {
         "name":"California Municipal Money Market",
         "ticker":"VCTXX",
         "assetClass":"Money Market",
         "expenseRatio":"0.16%",
         "price":"$1.00",
         "priceChange":"$0.00",
         "ytd":"0.01%",
         "oneyr":"0.01%",
         "fiveyr":"0.72%",
         "tenyr":"0.39%",
         "sinceInception":"2.09%"
      },
      {
         "name":"Municipal Money Market",
         "ticker":"VMSXX",
         "assetClass":"Money Market",
         "expenseRatio":"0.15%",
         "price":"$1.00",
         "priceChange":"$0.00",
         "ytd":"0.01%",
         "oneyr":"0.01%",
         "fiveyr":"0.80%",
         "tenyr":"0.44%",
         "sinceInception":"2.76%"
      },
      {
         "name":"New York Municipal Money Market",
         "ticker":"VYFXX",
         "assetClass":"Money Market",
         "expenseRatio":"0.16%",
         "price":"$1.00",
         "priceChange":"$0.00",
         "ytd":"0.01%",
         "oneyr":"0.01%",
         "fiveyr":"0.77%",
         "tenyr":"0.42%",
         "sinceInception":"1.36%"
      },
      {
         "name":"GNMA",
         "ticker":"VFIIX",
         "assetClass":"Bond - Inter-term Government",
         "expenseRatio":"0.21%",
         "price":"$10.56",
         "priceChange":"-$0.01",
         "ytd":"-0.96%",
         "oneyr":"-0.40%",
         "fiveyr":"2.27%",
         "tenyr":"2.17%",
         "sinceInception":"6.77%"
      },
      {
         "name":"Inflation-Protected Securities",
         "ticker":"VIPSX",
         "assetClass":"Bond - Inter-term Government",
         "expenseRatio":"0.20%",
         "price":"$14.66",
         "priceChange":"$0.00",
         "ytd":"4.69%",
         "oneyr":"6.59%",
         "fiveyr":"5.02%",
         "tenyr":"2.88%",
         "sinceInception":"5.37%"
      },
      {
         "name":"Intermediate-Term Bond Index  Admiral Shares",
         "ticker":"VBILX",
         "assetClass":"Bond - Inter-term Investment",
         "expenseRatio":"0.07%",
         "price":"$12.07",
         "priceChange":"-$0.01",
         "ytd":"-2.02%",
         "oneyr":"-1.89%",
         "fiveyr":"4.19%",
         "tenyr":"3.70%",
         "sinceInception":"4.95%"
      },
      {
         "name":"Intermediate-Term Treasury",
         "ticker":"VFITX",
         "assetClass":"Bond - Inter-term Government",
         "expenseRatio":"0.20%",
         "price":"$11.36",
         "priceChange":"$0.00",
         "ytd":"-1.89%",
         "oneyr":"-1.81%",
         "fiveyr":"2.95%",
         "tenyr":"2.22%",
         "sinceInception":"5.38%"
      },
      {
         "name":"Intermediate-Term Treasury Index  Admiral Shares",
         "ticker":"VSIGX",
         "assetClass":"Bond - Inter-term Government",
         "expenseRatio":"0.07%",
         "price":"$22.71",
         "priceChange":"$0.01",
         "ytd":"-2.14%",
         "oneyr":"-2.24%",
         "fiveyr":"2.84%",
         "tenyr":"2.19%",
         "sinceInception":"2.64%"
      },
      {
         "name":"Long-Term Bond Index  Admiral Shares",
         "ticker":"VBLAX",
         "assetClass":"Bond - Long-term Investment",
         "expenseRatio":"0.07%",
         "price":"$15.76",
         "priceChange":"-$0.11",
         "ytd":"-2.38%",
         "oneyr":"-2.16%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"10.55%"
      },
      {
         "name":"Long-Term Treasury",
         "ticker":"VUSTX",
         "assetClass":"Bond - Long-term Government",
         "expenseRatio":"0.20%",
         "price":"$12.92",
         "priceChange":"-$0.08",
         "ytd":"-3.74%",
         "oneyr":"-3.79%",
         "fiveyr":"6.84%",
         "tenyr":"4.93%",
         "sinceInception":"7.54%"
      },
      {
         "name":"Long-Term Treasury Index  Admiral Shares",
         "ticker":"VLGSX",
         "assetClass":"Bond - Long-term Government",
         "expenseRatio":"0.07%",
         "price":"$30.42",
         "priceChange":"-$0.18",
         "ytd":"-4.09%",
         "oneyr":"-4.32%",
         "fiveyr":"6.75%",
         "tenyr":"4.92%",
         "sinceInception":"6.77%"
      },
      {
         "name":"Mortgage-Backed Securities Index  Admiral Shares",
         "ticker":"VMBSX",
         "assetClass":"Bond - Inter-term Government",
         "expenseRatio":"0.07%",
         "price":"$21.16",
         "priceChange":"-$0.01",
         "ytd":"-1.26%",
         "oneyr":"-0.87%",
         "fiveyr":"2.37%",
         "tenyr":"2.22%",
         "sinceInception":"2.65%"
      },
      {
         "name":"Short-Term Bond Index  Admiral Shares",
         "ticker":"VBIRX",
         "assetClass":"Bond - Short-term Investment",
         "expenseRatio":"0.07%",
         "price":"$10.65",
         "priceChange":"$0.00",
         "ytd":"-0.92%",
         "oneyr":"-0.76%",
         "fiveyr":"2.23%",
         "tenyr":"1.73%",
         "sinceInception":"2.83%"
      },
      {
         "name":"Short-Term Federal",
         "ticker":"VSGBX",
         "assetClass":"Bond - Short-term Government",
         "expenseRatio":"0.20%",
         "price":"$10.86",
         "priceChange":"$0.00",
         "ytd":"-0.53%",
         "oneyr":"-0.13%",
         "fiveyr":"1.98%",
         "tenyr":"1.43%",
         "sinceInception":"4.53%"
      },
      {
         "name":"Short-Term Inflation-Protected Securities Index  Admiral Shares",
         "ticker":"VTAPX",
         "assetClass":"Bond - Short-term Government",
         "expenseRatio":"0.06%",
         "price":"$26.11",
         "priceChange":"$0.01",
         "ytd":"4.81%",
         "oneyr":"5.91%",
         "fiveyr":"3.26%",
         "tenyr":"—",
         "sinceInception":"1.77%"
      },
      {
         "name":"Short-Term Treasury",
         "ticker":"VFISX",
         "assetClass":"Bond - Short-term Government",
         "expenseRatio":"0.20%",
         "price":"$10.63",
         "priceChange":"$0.00",
         "ytd":"-0.79%",
         "oneyr":"-0.56%",
         "fiveyr":"1.71%",
         "tenyr":"1.15%",
         "sinceInception":"3.73%"
      },
      {
         "name":"Short-Term Treasury Index  Admiral Shares",
         "ticker":"VSBSX",
         "assetClass":"Bond - Short-term Government",
         "expenseRatio":"0.07%",
         "price":"$20.37",
         "priceChange":"$0.00",
         "ytd":"-0.58%",
         "oneyr":"-0.37%",
         "fiveyr":"1.60%",
         "tenyr":"1.05%",
         "sinceInception":"1.18%"
      },
      {
         "name":"Total Bond Market Index  Admiral Shares",
         "ticker":"VBTLX",
         "assetClass":"Bond - Inter-term Investment",
         "expenseRatio":"0.05%",
         "price":"$11.23",
         "priceChange":"-$0.02",
         "ytd":"-1.52%",
         "oneyr":"-1.12%",
         "fiveyr":"3.71%",
         "tenyr":"3.01%",
         "sinceInception":"4.12%"
      },
      {
         "name":"Core Bond",
         "ticker":"VCORX",
         "assetClass":"Bond - Inter-term Investment",
         "expenseRatio":"0.25%",
         "price":"$10.65",
         "priceChange":"-$0.02",
         "ytd":"-1.33%",
         "oneyr":"-0.85%",
         "fiveyr":"4.17%",
         "tenyr":"—",
         "sinceInception":"3.70%"
      },
      {
         "name":"Core-Plus Bond",
         "ticker":"VCPIX",
         "assetClass":"Bond - Inter-term Investment",
         "expenseRatio":"0.30%",
         "price":"$10.03",
         "priceChange":"-$0.01",
         "ytd":"—",
         "oneyr":"—",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"0.42%"
      },
      {
         "name":"Intermediate-Term Corporate Bond Index  Admiral Shares",
         "ticker":"VICSX",
         "assetClass":"Bond - Inter-term Investment",
         "expenseRatio":"0.07%",
         "price":"$25.26",
         "priceChange":"-$0.03",
         "ytd":"-1.47%",
         "oneyr":"-1.33%",
         "fiveyr":"4.95%",
         "tenyr":"4.96%",
         "sinceInception":"5.37%"
      },
      {
         "name":"Intermediate-Term Investment-Grade",
         "ticker":"VFICX",
         "assetClass":"Bond - Inter-term Investment",
         "expenseRatio":"0.20%",
         "price":"$10.06",
         "priceChange":"-$0.02",
         "ytd":"-1.21%",
         "oneyr":"-0.92%",
         "fiveyr":"4.46%",
         "tenyr":"4.28%",
         "sinceInception":"5.56%"
      },
      {
         "name":"Long-Term Corporate Bond Index  Admiral Shares",
         "ticker":"VLTCX",
         "assetClass":"Bond - Long-term Investment",
         "expenseRatio":"0.07%",
         "price":"$28.52",
         "priceChange":"-$0.21",
         "ytd":"-1.46%",
         "oneyr":"-1.20%",
         "fiveyr":"7.95%",
         "tenyr":"6.95%",
         "sinceInception":"7.59%"
      },
      {
         "name":"Long-Term Investment-Grade",
         "ticker":"VWESX",
         "assetClass":"Bond - Long-term Investment",
         "expenseRatio":"0.22%",
         "price":"$11.12",
         "priceChange":"-$0.08",
         "ytd":"-2.47%",
         "oneyr":"-1.63%",
         "fiveyr":"7.81%",
         "tenyr":"6.94%",
         "sinceInception":"8.33%"
      },
      {
         "name":"Short-Term Corporate Bond Index  Admiral Shares",
         "ticker":"VSCSX",
         "assetClass":"Bond - Short-term Investment",
         "expenseRatio":"0.07%",
         "price":"$22.19",
         "priceChange":"$0.00",
         "ytd":"-0.50%",
         "oneyr":"-0.13%",
         "fiveyr":"2.94%",
         "tenyr":"2.83%",
         "sinceInception":"2.70%"
      },
      {
         "name":"Short-Term Investment-Grade",
         "ticker":"VFSTX",
         "assetClass":"Bond - Short-term Investment",
         "expenseRatio":"0.20%",
         "price":"$10.81",
         "priceChange":"$0.00",
         "ytd":"-0.47%",
         "oneyr":"-0.12%",
         "fiveyr":"2.64%",
         "tenyr":"2.45%",
         "sinceInception":"5.71%"
      },
      {
         "name":"Ultra-Short-Term Bond",
         "ticker":"VUBFX",
         "assetClass":"Bond - Short-term Investment",
         "expenseRatio":"0.20%",
         "price":"$10.03",
         "priceChange":"$0.00",
         "ytd":"0.08%",
         "oneyr":"0.25%",
         "fiveyr":"1.74%",
         "tenyr":"—",
         "sinceInception":"1.49%"
      },
      {
         "name":"High-Yield Corporate",
         "ticker":"VWEHX",
         "assetClass":"Bond - Inter-term Low Quality",
         "expenseRatio":"0.23%",
         "price":"$5.92",
         "priceChange":"$0.00",
         "ytd":"3.04%",
         "oneyr":"3.18%",
         "fiveyr":"5.53%",
         "tenyr":"6.16%",
         "sinceInception":"8.12%"
      },
      {
         "name":"California Intermediate-Term Tax-Exempt",
         "ticker":"VCAIX",
         "assetClass":"Bond - Inter-term State Muni",
         "expenseRatio":"0.17%",
         "price":"$12.22",
         "priceChange":"$0.01",
         "ytd":"0.80%",
         "oneyr":"1.13%",
         "fiveyr":"3.85%",
         "tenyr":"3.66%",
         "sinceInception":"4.58%"
      },
      {
         "name":"California Long-Term Tax-Exempt",
         "ticker":"VCITX",
         "assetClass":"Bond - Long-term State Muni",
         "expenseRatio":"0.17%",
         "price":"$12.76",
         "priceChange":"$0.00",
         "ytd":"1.87%",
         "oneyr":"2.22%",
         "fiveyr":"4.96%",
         "tenyr":"4.73%",
         "sinceInception":"5.80%"
      },
      {
         "name":"High-Yield Tax-Exempt",
         "ticker":"VWAHX",
         "assetClass":"Bond - Long-term National Muni",
         "expenseRatio":"0.17%",
         "price":"$12.08",
         "priceChange":"$0.00",
         "ytd":"3.82%",
         "oneyr":"4.96%",
         "fiveyr":"5.66%",
         "tenyr":"5.12%",
         "sinceInception":"6.43%"
      },
      {
         "name":"Intermediate-Term Tax-Exempt",
         "ticker":"VWITX",
         "assetClass":"Bond - Inter-term National Muni",
         "expenseRatio":"0.17%",
         "price":"$14.72",
         "priceChange":"$0.00",
         "ytd":"1.06%",
         "oneyr":"1.62%",
         "fiveyr":"3.92%",
         "tenyr":"3.47%",
         "sinceInception":"5.24%"
      },
      {
         "name":"Limited-Term Tax-Exempt",
         "ticker":"VMLTX",
         "assetClass":"Bond - Short-term National Muni",
         "expenseRatio":"0.17%",
         "price":"$11.17",
         "priceChange":"$0.00",
         "ytd":"0.37%",
         "oneyr":"0.70%",
         "fiveyr":"2.30%",
         "tenyr":"1.71%",
         "sinceInception":"3.84%"
      },
      {
         "name":"Long-Term Tax-Exempt",
         "ticker":"VWLTX",
         "assetClass":"Bond - Long-term National Muni",
         "expenseRatio":"0.17%",
         "price":"$12.19",
         "priceChange":"$0.00",
         "ytd":"2.15%",
         "oneyr":"2.97%",
         "fiveyr":"5.07%",
         "tenyr":"4.61%",
         "sinceInception":"5.77%"
      },
      {
         "name":"Massachusetts Tax-Exempt",
         "ticker":"VMATX",
         "assetClass":"Bond - Long-term State Muni",
         "expenseRatio":"0.13%",
         "price":"$11.41",
         "priceChange":"$0.00",
         "ytd":"1.94%",
         "oneyr":"2.52%",
         "fiveyr":"4.94%",
         "tenyr":"4.20%",
         "sinceInception":"4.47%"
      },
      {
         "name":"New Jersey Long-Term Tax-Exempt",
         "ticker":"VNJTX",
         "assetClass":"Bond - Long-term State Muni",
         "expenseRatio":"0.17%",
         "price":"$12.75",
         "priceChange":"$0.00",
         "ytd":"3.03%",
         "oneyr":"4.26%",
         "fiveyr":"5.73%",
         "tenyr":"4.72%",
         "sinceInception":"5.80%"
      },
      {
         "name":"New York Long-Term Tax-Exempt",
         "ticker":"VNYTX",
         "assetClass":"Bond - Long-term State Muni",
         "expenseRatio":"0.17%",
         "price":"$12.21",
         "priceChange":"$0.00",
         "ytd":"2.44%",
         "oneyr":"3.34%",
         "fiveyr":"4.70%",
         "tenyr":"4.30%",
         "sinceInception":"5.56%"
      },
      {
         "name":"Ohio Long-Term Tax-Exempt",
         "ticker":"VOHIX",
         "assetClass":"Bond - Long-term State Muni",
         "expenseRatio":"0.13%",
         "price":"$13.22",
         "priceChange":"$0.01",
         "ytd":"2.13%",
         "oneyr":"2.59%",
         "fiveyr":"5.13%",
         "tenyr":"4.62%",
         "sinceInception":"5.70%"
      },
      {
         "name":"Pennsylvania Long-Term Tax-Exempt",
         "ticker":"VPAIX",
         "assetClass":"Bond - Long-term State Muni",
         "expenseRatio":"0.17%",
         "price":"$12.13",
         "priceChange":"$0.00",
         "ytd":"2.35%",
         "oneyr":"2.99%",
         "fiveyr":"5.18%",
         "tenyr":"4.54%",
         "sinceInception":"5.78%"
      },
      {
         "name":"Short-Term Tax-Exempt",
         "ticker":"VWSTX",
         "assetClass":"Bond - Short-term National Muni",
         "expenseRatio":"0.17%",
         "price":"$15.88",
         "priceChange":"$0.00",
         "ytd":"0.16%",
         "oneyr":"0.32%",
         "fiveyr":"1.42%",
         "tenyr":"1.01%",
         "sinceInception":"3.66%"
      },
      {
         "name":"Tax-Exempt Bond Index  Admiral Shares",
         "ticker":"VTEAX",
         "assetClass":"Bond - Inter-term National Muni",
         "expenseRatio":"0.09%",
         "price":"$22.00",
         "priceChange":"$0.01",
         "ytd":"1.40%",
         "oneyr":"1.92%",
         "fiveyr":"4.13%",
         "tenyr":"—",
         "sinceInception":"3.53%"
      },
      {
         "name":"Target Retirement 2015",
         "ticker":"VTXVX",
         "assetClass":"Balanced",
         "expenseRatio":"0.12%",
         "price":"$16.45",
         "priceChange":"-$0.07",
         "ytd":"4.58%",
         "oneyr":"6.72%",
         "fiveyr":"7.71%",
         "tenyr":"7.39%",
         "sinceInception":"6.42%"
      },
      {
         "name":"Target Retirement 2020",
         "ticker":"VTWNX",
         "assetClass":"Balanced",
         "expenseRatio":"0.13%",
         "price":"$36.47",
         "priceChange":"-$0.20",
         "ytd":"6.36%",
         "oneyr":"9.25%",
         "fiveyr":"9.19%",
         "tenyr":"8.57%",
         "sinceInception":"6.86%"
      },
      {
         "name":"Target Retirement 2025",
         "ticker":"VTTVX",
         "assetClass":"Balanced",
         "expenseRatio":"0.13%",
         "price":"$23.15",
         "priceChange":"-$0.15",
         "ytd":"7.47%",
         "oneyr":"10.86%",
         "fiveyr":"10.21%",
         "tenyr":"9.40%",
         "sinceInception":"7.39%"
      },
      {
         "name":"Target Retirement 2030",
         "ticker":"VTHRX",
         "assetClass":"Balanced",
         "expenseRatio":"0.14%",
         "price":"$44.04",
         "priceChange":"-$0.34",
         "ytd":"8.61%",
         "oneyr":"12.49%",
         "fiveyr":"11.03%",
         "tenyr":"10.11%",
         "sinceInception":"7.52%"
      },
      {
         "name":"Target Retirement 2035",
         "ticker":"VTTHX",
         "assetClass":"Balanced",
         "expenseRatio":"0.14%",
         "price":"$27.69",
         "priceChange":"-$0.23",
         "ytd":"9.79%",
         "oneyr":"14.11%",
         "fiveyr":"11.81%",
         "tenyr":"10.80%",
         "sinceInception":"8.18%"
      },
      {
         "name":"Target Retirement 2040",
         "ticker":"VFORX",
         "assetClass":"Balanced",
         "expenseRatio":"0.14%",
         "price":"$49.12",
         "priceChange":"-$0.45",
         "ytd":"10.96%",
         "oneyr":"15.76%",
         "fiveyr":"12.60%",
         "tenyr":"11.34%",
         "sinceInception":"8.15%"
      },
      {
         "name":"Target Retirement 2045",
         "ticker":"VTIVX",
         "assetClass":"Balanced",
         "expenseRatio":"0.15%",
         "price":"$31.61",
         "priceChange":"-$0.31",
         "ytd":"12.13%",
         "oneyr":"17.39%",
         "fiveyr":"13.19%",
         "tenyr":"11.65%",
         "sinceInception":"8.81%"
      },
      {
         "name":"Target Retirement 2050",
         "ticker":"VFIFX",
         "assetClass":"Balanced",
         "expenseRatio":"0.15%",
         "price":"$51.04",
         "priceChange":"-$0.50",
         "ytd":"12.30%",
         "oneyr":"17.60%",
         "fiveyr":"13.24%",
         "tenyr":"11.67%",
         "sinceInception":"8.39%"
      },
      {
         "name":"Target Retirement 2055",
         "ticker":"VFFVX",
         "assetClass":"Balanced",
         "expenseRatio":"0.15%",
         "price":"$55.41",
         "priceChange":"-$0.55",
         "ytd":"12.30%",
         "oneyr":"17.60%",
         "fiveyr":"13.24%",
         "tenyr":"11.66%",
         "sinceInception":"11.42%"
      },
      {
         "name":"Target Retirement 2060",
         "ticker":"VTTSX",
         "assetClass":"Balanced",
         "expenseRatio":"0.15%",
         "price":"$48.96",
         "priceChange":"-$0.48",
         "ytd":"12.32%",
         "oneyr":"17.61%",
         "fiveyr":"13.24%",
         "tenyr":"—",
         "sinceInception":"11.34%"
      },
      {
         "name":"Target Retirement 2065",
         "ticker":"VLXVX",
         "assetClass":"Balanced",
         "expenseRatio":"0.15%",
         "price":"$30.89",
         "priceChange":"-$0.30",
         "ytd":"12.33%",
         "oneyr":"17.59%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"12.01%"
      },
      {
         "name":"Target Retirement Income",
         "ticker":"VTINX",
         "assetClass":"Balanced",
         "expenseRatio":"0.12%",
         "price":"$15.38",
         "priceChange":"-$0.06",
         "ytd":"4.12%",
         "oneyr":"6.05%",
         "fiveyr":"6.83%",
         "tenyr":"5.83%",
         "sinceInception":"5.59%"
      },
      {
         "name":"LifeStrategy Conservative Growth",
         "ticker":"VSCGX",
         "assetClass":"Balanced",
         "expenseRatio":"0.12%",
         "price":"$23.47",
         "priceChange":"-$0.12",
         "ytd":"4.62%",
         "oneyr":"6.94%",
         "fiveyr":"7.98%",
         "tenyr":"7.02%",
         "sinceInception":"7.04%"
      },
      {
         "name":"LifeStrategy Growth",
         "ticker":"VASGX",
         "assetClass":"Balanced",
         "expenseRatio":"0.14%",
         "price":"$44.27",
         "priceChange":"-$0.40",
         "ytd":"10.76%",
         "oneyr":"15.46%",
         "fiveyr":"12.22%",
         "tenyr":"10.79%",
         "sinceInception":"8.57%"
      },
      {
         "name":"LifeStrategy Income",
         "ticker":"VASIX",
         "assetClass":"Balanced",
         "expenseRatio":"0.11%",
         "price":"$17.38",
         "priceChange":"-$0.05",
         "ytd":"1.52%",
         "oneyr":"2.80%",
         "fiveyr":"5.76%",
         "tenyr":"5.04%",
         "sinceInception":"6.19%"
      },
      {
         "name":"LifeStrategy Moderate Growth",
         "ticker":"VSMGX",
         "assetClass":"Balanced",
         "expenseRatio":"0.13%",
         "price":"$33.83",
         "priceChange":"-$0.24",
         "ytd":"7.61%",
         "oneyr":"11.10%",
         "fiveyr":"10.11%",
         "tenyr":"8.93%",
         "sinceInception":"7.93%"
      },
      {
         "name":"Balanced Index  Admiral Shares",
         "ticker":"VBIAX",
         "assetClass":"Balanced",
         "expenseRatio":"0.07%",
         "price":"$48.64",
         "priceChange":"-$0.39",
         "ytd":"11.33%",
         "oneyr":"14.84%",
         "fiveyr":"12.15%",
         "tenyr":"10.85%",
         "sinceInception":"7.26%"
      },
      {
         "name":"Managed Allocation",
         "ticker":"VPGDX",
         "assetClass":"Balanced",
         "expenseRatio":"0.28%",
         "price":"$18.95",
         "priceChange":"-$0.14",
         "ytd":"10.59%",
         "oneyr":"13.66%",
         "fiveyr":"8.04%",
         "tenyr":"7.78%",
         "sinceInception":"5.71%"
      },
      {
         "name":"STAR",
         "ticker":"VGSTX",
         "assetClass":"Balanced",
         "expenseRatio":"0.31%",
         "price":"$33.03",
         "priceChange":"-$0.30",
         "ytd":"6.72%",
         "oneyr":"12.09%",
         "fiveyr":"12.65%",
         "tenyr":"10.67%",
         "sinceInception":"9.78%"
      },
      {
         "name":"Tax-Managed Balanced  Admiral Shares",
         "ticker":"VTMFX",
         "assetClass":"Balanced",
         "expenseRatio":"0.09%",
         "price":"$41.68",
         "priceChange":"-$0.23",
         "ytd":"10.74%",
         "oneyr":"13.51%",
         "fiveyr":"10.80%",
         "tenyr":"9.67%",
         "sinceInception":"8.00%"
      },
      {
         "name":"Wellesley Income",
         "ticker":"VWINX",
         "assetClass":"Balanced",
         "expenseRatio":"0.23%",
         "price":"$28.57",
         "priceChange":"-$1.34",
         "ytd":"7.08%",
         "oneyr":"7.36%",
         "fiveyr":"7.83%",
         "tenyr":"7.68%",
         "sinceInception":"9.64%"
      },
      {
         "name":"Wellington",
         "ticker":"VWELX",
         "assetClass":"Balanced",
         "expenseRatio":"0.24%",
         "price":"$50.74",
         "priceChange":"-$0.38",
         "ytd":"15.99%",
         "oneyr":"17.16%",
         "fiveyr":"11.94%",
         "tenyr":"11.14%",
         "sinceInception":"8.43%"
      },
      {
         "name":"Global Wellesley Income",
         "ticker":"VGWIX",
         "assetClass":"Balanced",
         "expenseRatio":"0.41%",
         "price":"$21.86",
         "priceChange":"-$0.06",
         "ytd":"5.26%",
         "oneyr":"5.72%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"4.68%"
      },
      {
         "name":"Global Wellington",
         "ticker":"VGWLX",
         "assetClass":"Balanced",
         "expenseRatio":"0.42%",
         "price":"$25.59",
         "priceChange":"-$0.14",
         "ytd":"10.87%",
         "oneyr":"11.72%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"8.29%"
      },
      {
         "name":"500 Index  Admiral Shares",
         "ticker":"VFIAX",
         "assetClass":"Stock - Large-Cap Blend",
         "expenseRatio":"0.04%",
         "price":"$421.39",
         "priceChange":"-$6.41",
         "ytd":"23.27%",
         "oneyr":"27.89%",
         "fiveyr":"17.86%",
         "tenyr":"16.12%",
         "sinceInception":"8.01%"
      },
      {
         "name":"Diversified Equity",
         "ticker":"VDEQX",
         "assetClass":"Stock - Large-Cap Blend",
         "expenseRatio":"0.35%",
         "price":"$53.89",
         "priceChange":"-$0.77",
         "ytd":"16.34%",
         "oneyr":"24.86%",
         "fiveyr":"18.77%",
         "tenyr":"16.26%",
         "sinceInception":"10.68%"
      },
      {
         "name":"Dividend Appreciation Index  Admiral Shares",
         "ticker":"VDADX",
         "assetClass":"Stock - Large-Cap Blend",
         "expenseRatio":"0.08%",
         "price":"$44.69",
         "priceChange":"-$0.49",
         "ytd":"18.55%",
         "oneyr":"19.03%",
         "fiveyr":"16.02%",
         "tenyr":"—",
         "sinceInception":"12.58%"
      },
      {
         "name":"Dividend Growth",
         "ticker":"VDIGX",
         "assetClass":"Stock - Large-Cap Blend",
         "expenseRatio":"0.26%",
         "price":"$39.37",
         "priceChange":"-$0.39",
         "ytd":"19.96%",
         "oneyr":"18.77%",
         "fiveyr":"15.54%",
         "tenyr":"14.01%",
         "sinceInception":"9.33%"
      },
      {
         "name":"Equity Income",
         "ticker":"VEIPX",
         "assetClass":"Stock - Large-Cap Value",
         "expenseRatio":"0.28%",
         "price":"$42.48",
         "priceChange":"-$0.36",
         "ytd":"21.18%",
         "oneyr":"21.56%",
         "fiveyr":"11.75%",
         "tenyr":"12.75%",
         "sinceInception":"10.34%"
      },
      {
         "name":"FTSE Social Index  Admiral Shares",
         "ticker":"VFTAX",
         "assetClass":"Stock - Large-Cap Growth",
         "expenseRatio":"0.14%",
         "price":"$44.53",
         "priceChange":"-$0.53",
         "ytd":"22.43%",
         "oneyr":"28.25%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"24.83%"
      },
      {
         "name":"Growth and Income",
         "ticker":"VQNPX",
         "assetClass":"Stock - Large-Cap Blend",
         "expenseRatio":"0.32%",
         "price":"$61.13",
         "priceChange":"-$10.23",
         "ytd":"23.39%",
         "oneyr":"28.53%",
         "fiveyr":"17.15%",
         "tenyr":"16.06%",
         "sinceInception":"10.92%"
      },
      {
         "name":"Growth Index  Admiral Shares",
         "ticker":"VIGAX",
         "assetClass":"Stock - Large-Cap Growth",
         "expenseRatio":"0.05%",
         "price":"$157.98",
         "priceChange":"-$1.99",
         "ytd":"21.56%",
         "oneyr":"30.34%",
         "fiveyr":"24.61%",
         "tenyr":"19.01%",
         "sinceInception":"9.06%"
      },
      {
         "name":"High Dividend Yield Index  Admiral Shares",
         "ticker":"VHYAX",
         "assetClass":"Stock - Large-Cap Value",
         "expenseRatio":"0.08%",
         "price":"$32.60",
         "priceChange":"-$0.26",
         "ytd":"21.65%",
         "oneyr":"22.23%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"12.56%"
      },
      {
         "name":"Large-Cap Index  Admiral Shares",
         "ticker":"VLCAX",
         "assetClass":"Stock - Large-Cap Blend",
         "expenseRatio":"0.05%",
         "price":"$107.11",
         "priceChange":"-$1.25",
         "ytd":"21.78%",
         "oneyr":"27.04%",
         "fiveyr":"18.22%",
         "tenyr":"16.24%",
         "sinceInception":"10.58%"
      },
      {
         "name":"PRIMECAP",
         "ticker":"VPMCX",
         "assetClass":"Stock - Large-Cap Growth",
         "expenseRatio":"0.38%",
         "price":"$155.87",
         "priceChange":"-$18.87",
         "ytd":"16.08%",
         "oneyr":"24.16%",
         "fiveyr":"17.94%",
         "tenyr":"17.11%",
         "sinceInception":"13.98%"
      },
      {
         "name":"PRIMECAP  Admiral Shares",
         "ticker":"VPMAX",
         "assetClass":"Stock - Large-Cap Growth",
         "expenseRatio":"0.31%",
         "price":"$161.47",
         "priceChange":"-$19.72",
         "ytd":"16.16%",
         "oneyr":"24.24%",
         "fiveyr":"18.02%",
         "tenyr":"17.20%",
         "sinceInception":"11.58%"
      },
      {
         "name":"PRIMECAP Core",
         "ticker":"VPCCX",
         "assetClass":"Stock - Large-Cap Blend",
         "expenseRatio":"0.46%",
         "price":"$32.13",
         "priceChange":"-$2.78",
         "ytd":"18.87%",
         "oneyr":"24.53%",
         "fiveyr":"15.88%",
         "tenyr":"15.78%",
         "sinceInception":"11.55%"
      },
      {
         "name":"Tax-Managed Capital Appreciation  Admiral Shares",
         "ticker":"VTCLX",
         "assetClass":"Stock - Large-Cap Blend",
         "expenseRatio":"0.09%",
         "price":"$238.04",
         "priceChange":"-$2.87",
         "ytd":"21.46%",
         "oneyr":"26.96%",
         "fiveyr":"18.10%",
         "tenyr":"16.29%",
         "sinceInception":"10.91%"
      },
      {
         "name":"Total Stock Market Index  Admiral Shares",
         "ticker":"VTSAX",
         "assetClass":"Stock - Large-Cap Blend",
         "expenseRatio":"0.04%",
         "price":"$112.96",
         "priceChange":"-$1.40",
         "ytd":"20.37%",
         "oneyr":"26.49%",
         "fiveyr":"17.55%",
         "tenyr":"15.95%",
         "sinceInception":"8.45%"
      },
      {
         "name":"U.S. Growth",
         "ticker":"VWUSX",
         "assetClass":"Stock - Large-Cap Growth",
         "expenseRatio":"0.38%",
         "price":"$62.39",
         "priceChange":"-$1.06",
         "ytd":"7.78%",
         "oneyr":"21.08%",
         "fiveyr":"26.44%",
         "tenyr":"20.11%",
         "sinceInception":"11.35%"
      },
      {
         "name":"Value Index  Admiral Shares",
         "ticker":"VVIAX",
         "assetClass":"Stock - Large-Cap Value",
         "expenseRatio":"0.05%",
         "price":"$55.62",
         "priceChange":"-$0.58",
         "ytd":"21.86%",
         "oneyr":"22.59%",
         "fiveyr":"11.60%",
         "tenyr":"13.25%",
         "sinceInception":"7.23%"
      },
      {
         "name":"Windsor",
         "ticker":"VWNDX",
         "assetClass":"Stock - Large-Cap Value",
         "expenseRatio":"0.29%",
         "price":"$23.06",
         "priceChange":"-$2.92",
         "ytd":"22.01%",
         "oneyr":"25.85%",
         "fiveyr":"12.30%",
         "tenyr":"13.46%",
         "sinceInception":"11.39%"
      },
      {
         "name":"Windsor II",
         "ticker":"VWNFX",
         "assetClass":"Stock - Large-Cap Value",
         "expenseRatio":"0.34%",
         "price":"$44.24",
         "priceChange":"-$3.94",
         "ytd":"23.63%",
         "oneyr":"28.58%",
         "fiveyr":"14.49%",
         "tenyr":"13.85%",
         "sinceInception":"11.16%"
      },
      {
         "name":"Capital Opportunity",
         "ticker":"VHCOX",
         "assetClass":"Stock - Mid-Cap Growth",
         "expenseRatio":"0.44%",
         "price":"$80.18",
         "priceChange":"-$9.99",
         "ytd":"15.67%",
         "oneyr":"24.92%",
         "fiveyr":"18.74%",
         "tenyr":"18.08%",
         "sinceInception":"13.20%"
      },
      {
         "name":"Capital Opportunity  Admiral Shares",
         "ticker":"VHCAX",
         "assetClass":"Stock - Mid-Cap Growth",
         "expenseRatio":"0.37%",
         "price":"$185.04",
         "priceChange":"-$23.27",
         "ytd":"15.75%",
         "oneyr":"25.00%",
         "fiveyr":"18.83%",
         "tenyr":"18.16%",
         "sinceInception":"12.25%"
      },
      {
         "name":"Extended Market Index  Admiral Shares",
         "ticker":"VEXAX",
         "assetClass":"Stock - Mid-Cap Blend",
         "expenseRatio":"0.06%",
         "price":"$133.10",
         "priceChange":"-$2.25",
         "ytd":"7.47%",
         "oneyr":"19.90%",
         "fiveyr":"15.59%",
         "tenyr":"14.90%",
         "sinceInception":"9.46%"
      },
      {
         "name":"Mid-Cap Growth",
         "ticker":"VMGRX",
         "assetClass":"Stock - Mid-Cap Growth",
         "expenseRatio":"0.34%",
         "price":"$25.60",
         "priceChange":"-$9.82",
         "ytd":"4.12%",
         "oneyr":"14.49%",
         "fiveyr":"17.56%",
         "tenyr":"14.30%",
         "sinceInception":"11.20%"
      },
      {
         "name":"Mid-Cap Growth Index  Admiral Shares",
         "ticker":"VMGMX",
         "assetClass":"Stock - Mid-Cap Growth",
         "expenseRatio":"0.07%",
         "price":"$104.55",
         "priceChange":"-$1.43",
         "ytd":"14.82%",
         "oneyr":"23.70%",
         "fiveyr":"19.65%",
         "tenyr":"16.01%",
         "sinceInception":"16.27%"
      },
      {
         "name":"Mid-Cap Index  Admiral Shares",
         "ticker":"VIMAX",
         "assetClass":"Stock - Mid-Cap Blend",
         "expenseRatio":"0.05%",
         "price":"$301.67",
         "priceChange":"-$4.37",
         "ytd":"18.64%",
         "oneyr":"24.78%",
         "fiveyr":"15.13%",
         "tenyr":"14.64%",
         "sinceInception":"11.02%"
      },
      {
         "name":"Mid-Cap Value Index  Admiral Shares",
         "ticker":"VMVAX",
         "assetClass":"Stock - Mid-Cap Value",
         "expenseRatio":"0.07%",
         "price":"$74.58",
         "priceChange":"-$1.15",
         "ytd":"22.65%",
         "oneyr":"25.52%",
         "fiveyr":"10.51%",
         "tenyr":"13.03%",
         "sinceInception":"13.64%"
      },
      {
         "name":"Selected Value",
         "ticker":"VASVX",
         "assetClass":"Stock - Mid-Cap Value",
         "expenseRatio":"0.31%",
         "price":"$28.75",
         "priceChange":"-$3.01",
         "ytd":"19.83%",
         "oneyr":"27.03%",
         "fiveyr":"9.88%",
         "tenyr":"11.89%",
         "sinceInception":"9.09%"
      },
      {
         "name":"Strategic Equity",
         "ticker":"VSEQX",
         "assetClass":"Stock - Mid-Cap Blend",
         "expenseRatio":"0.17%",
         "price":"$36.52",
         "priceChange":"-$0.64",
         "ytd":"23.26%",
         "oneyr":"32.16%",
         "fiveyr":"12.25%",
         "tenyr":"14.41%",
         "sinceInception":"11.01%"
      },
      {
         "name":"Explorer",
         "ticker":"VEXPX",
         "assetClass":"Stock - Small-Cap Growth",
         "expenseRatio":"0.41%",
         "price":"$121.65",
         "priceChange":"-$22.68",
         "ytd":"10.44%",
         "oneyr":"23.18%",
         "fiveyr":"18.84%",
         "tenyr":"15.77%",
         "sinceInception":"9.94%"
      },
      {
         "name":"Explorer Value",
         "ticker":"VEVFX",
         "assetClass":"Stock - Small-Cap Value",
         "expenseRatio":"0.52%",
         "price":"$43.34",
         "priceChange":"-$0.87",
         "ytd":"20.38%",
         "oneyr":"31.93%",
         "fiveyr":"9.93%",
         "tenyr":"12.30%",
         "sinceInception":"11.62%"
      },
      {
         "name":"Small-Cap Growth Index  Admiral Shares",
         "ticker":"VSGAX",
         "assetClass":"Stock - Small-Cap Growth",
         "expenseRatio":"0.07%",
         "price":"$94.60",
         "priceChange":"-$1.42",
         "ytd":"0.85%",
         "oneyr":"12.63%",
         "fiveyr":"16.67%",
         "tenyr":"14.58%",
         "sinceInception":"15.24%"
      },
      {
         "name":"Small-Cap Index  Admiral Shares",
         "ticker":"VSMAX",
         "assetClass":"Stock - Small-Cap Blend",
         "expenseRatio":"0.05%",
         "price":"$103.19",
         "priceChange":"-$1.83",
         "ytd":"11.56%",
         "oneyr":"22.18%",
         "fiveyr":"13.13%",
         "tenyr":"13.79%",
         "sinceInception":"9.91%"
      },
      {
         "name":"Small-Cap Value Index  Admiral Shares",
         "ticker":"VSIAX",
         "assetClass":"Stock - Small-Cap Value",
         "expenseRatio":"0.07%",
         "price":"$72.91",
         "priceChange":"-$1.44",
         "ytd":"20.78%",
         "oneyr":"30.27%",
         "fiveyr":"9.87%",
         "tenyr":"12.87%",
         "sinceInception":"13.59%"
      },
      {
         "name":"Strategic Small-Cap Equity",
         "ticker":"VSTCX",
         "assetClass":"Stock - Small-Cap Blend",
         "expenseRatio":"0.26%",
         "price":"$36.76",
         "priceChange":"-$0.64",
         "ytd":"25.65%",
         "oneyr":"36.80%",
         "fiveyr":"11.03%",
         "tenyr":"13.33%",
         "sinceInception":"8.41%"
      },
      {
         "name":"Tax-Managed Small-Cap  Admiral Shares",
         "ticker":"VTMSX",
         "assetClass":"Stock - Small-Cap Blend",
         "expenseRatio":"0.09%",
         "price":"$88.46",
         "priceChange":"-$1.36",
         "ytd":"20.00%",
         "oneyr":"31.46%",
         "fiveyr":"12.17%",
         "tenyr":"14.08%",
         "sinceInception":"11.19%"
      },
      {
         "name":"Global Credit Bond",
         "ticker":"VGCIX",
         "assetClass":"International",
         "expenseRatio":"0.35%",
         "price":"$11.05",
         "priceChange":"-$0.02",
         "ytd":"-0.52%",
         "oneyr":"0.12%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"7.73%"
      },
      {
         "name":"Total International Bond Index  Admiral Shares",
         "ticker":"VTABX",
         "assetClass":"International",
         "expenseRatio":"0.11%",
         "price":"$22.93",
         "priceChange":"-$0.01",
         "ytd":"-1.24%",
         "oneyr":"-1.15%",
         "fiveyr":"3.30%",
         "tenyr":"—",
         "sinceInception":"3.56%"
      },
      {
         "name":"Emerging Markets Bond",
         "ticker":"VEMBX",
         "assetClass":"International",
         "expenseRatio":"0.60%",
         "price":"$11.68",
         "priceChange":"-$0.03",
         "ytd":"-1.66%",
         "oneyr":"-0.56%",
         "fiveyr":"8.43%",
         "tenyr":"—",
         "sinceInception":"8.74%"
      },
      {
         "name":"Emerging Markets Government Bond Index  Admiral Shares",
         "ticker":"VGAVX",
         "assetClass":"International",
         "expenseRatio":"0.25%",
         "price":"$19.36",
         "priceChange":"-$0.09",
         "ytd":"-2.55%",
         "oneyr":"-2.41%",
         "fiveyr":"4.27%",
         "tenyr":"—",
         "sinceInception":"3.94%"
      },
      {
         "name":"Global Capital Cycles",
         "ticker":"VGPMX",
         "assetClass":"International",
         "expenseRatio":"0.35%",
         "price":"$10.90",
         "priceChange":"-$0.08",
         "ytd":"14.16%",
         "oneyr":"24.73%",
         "fiveyr":"4.38%",
         "tenyr":"-5.41%",
         "sinceInception":"4.28%"
      },
      {
         "name":"Global Equity",
         "ticker":"VHGEX",
         "assetClass":"International",
         "expenseRatio":"0.45%",
         "price":"$36.99",
         "priceChange":"-$0.47",
         "ytd":"8.78%",
         "oneyr":"16.53%",
         "fiveyr":"15.45%",
         "tenyr":"12.94%",
         "sinceInception":"9.62%"
      },
      {
         "name":"Global ESG Select Stock",
         "ticker":"VEIGX",
         "assetClass":"International",
         "expenseRatio":"0.55%",
         "price":"$31.15",
         "priceChange":"-$0.18",
         "ytd":"17.47%",
         "oneyr":"18.69%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"19.48%"
      },
      {
         "name":"Total World Stock Index  Admiral Shares",
         "ticker":"VTWAX",
         "assetClass":"International",
         "expenseRatio":"0.10%",
         "price":"$36.55",
         "priceChange":"-$0.40",
         "ytd":"13.47%",
         "oneyr":"19.35%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"17.10%"
      },
      {
         "name":"Developed Markets Index  Admiral Shares",
         "ticker":"VTMGX",
         "assetClass":"International",
         "expenseRatio":"0.07%",
         "price":"$15.85",
         "priceChange":"-$0.09",
         "ytd":"7.43%",
         "oneyr":"12.51%",
         "fiveyr":"9.66%",
         "tenyr":"7.75%",
         "sinceInception":"4.69%"
      },
      {
         "name":"European Stock Index  Admiral Shares",
         "ticker":"VEUSX",
         "assetClass":"International",
         "expenseRatio":"0.10%",
         "price":"$81.74",
         "priceChange":"-$0.07",
         "ytd":"11.13%",
         "oneyr":"15.95%",
         "fiveyr":"10.51%",
         "tenyr":"7.81%",
         "sinceInception":"6.03%"
      },
      {
         "name":"FTSE All-World ex-US Index  Admiral Shares",
         "ticker":"VFWAX",
         "assetClass":"International",
         "expenseRatio":"0.11%",
         "price":"$36.82",
         "priceChange":"-$0.30",
         "ytd":"4.40%",
         "oneyr":"9.82%",
         "fiveyr":"9.47%",
         "tenyr":"6.90%",
         "sinceInception":"7.23%"
      },
      {
         "name":"FTSE All-World ex-US Small-Cap Index  Admiral Shares",
         "ticker":"VFSAX",
         "assetClass":"International",
         "expenseRatio":"0.16%",
         "price":"$31.44",
         "priceChange":"-$0.29",
         "ytd":"7.18%",
         "oneyr":"15.74%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"12.03%"
      },
      {
         "name":"Global ex-U.S. Real Estate Index  Admiral Shares",
         "ticker":"VGRLX",
         "assetClass":"International",
         "expenseRatio":"0.12%",
         "price":"$31.60",
         "priceChange":"-$2.18",
         "ytd":"2.31%",
         "oneyr":"5.96%",
         "fiveyr":"5.82%",
         "tenyr":"6.81%",
         "sinceInception":"5.04%"
      },
      {
         "name":"International Core Stock",
         "ticker":"VWICX",
         "assetClass":"International",
         "expenseRatio":"0.46%",
         "price":"$11.90",
         "priceChange":"-$0.09",
         "ytd":"8.01%",
         "oneyr":"11.98%",
         "fiveyr":"—",
         "tenyr":"—",
         "sinceInception":"10.51%"
      },
      {
         "name":"International Dividend Appreciation Index  Admiral Shares",
         "ticker":"VIAAX",
         "assetClass":"International",
         "expenseRatio":"0.20%",
         "price":"$40.20",
         "priceChange":"-$0.26",
         "ytd":"8.83%",
         "oneyr":"12.45%",
         "fiveyr":"12.47%",
         "tenyr":"—",
         "sinceInception":"11.15%"
      },
      {
         "name":"International Explorer",
         "ticker":"VINEX",
         "assetClass":"International",
         "expenseRatio":"0.39%",
         "price":"$20.35",
         "priceChange":"-$1.16",
         "ytd":"4.76%",
         "oneyr":"14.16%",
         "fiveyr":"10.08%",
         "tenyr":"9.37%",
         "sinceInception":"9.10%"
      },
      {
         "name":"International Growth",
         "ticker":"VWIGX",
         "assetClass":"International",
         "expenseRatio":"0.43%",
         "price":"$41.97",
         "priceChange":"-$0.53",
         "ytd":"-5.01%",
         "oneyr":"6.96%",
         "fiveyr":"21.39%",
         "tenyr":"13.64%",
         "sinceInception":"11.38%"
      },
      {
         "name":"International High Dividend Yield Index  Admiral Shares",
         "ticker":"VIHAX",
         "assetClass":"International",
         "expenseRatio":"0.28%",
         "price":"$31.52",
         "priceChange":"-$0.19",
         "ytd":"11.49%",
         "oneyr":"14.42%",
         "fiveyr":"7.07%",
         "tenyr":"—",
         "sinceInception":"7.67%"
      },
      {
         "name":"International Value",
         "ticker":"VTRIX",
         "assetClass":"International",
         "expenseRatio":"0.35%",
         "price":"$40.02",
         "priceChange":"-$2.20",
         "ytd":"3.92%",
         "oneyr":"10.50%",
         "fiveyr":"8.45%",
         "tenyr":"6.76%",
         "sinceInception":"8.52%"
      },
      {
         "name":"Pacific Stock Index  Admiral Shares",
         "ticker":"VPADX",
         "assetClass":"International",
         "expenseRatio":"0.10%",
         "price":"$95.10",
         "priceChange":"-$0.97",
         "ytd":"-0.25%",
         "oneyr":"4.47%",
         "fiveyr":"8.19%",
         "tenyr":"7.31%",
         "sinceInception":"5.71%"
      },
      {
         "name":"Total International Stock Index  Admiral Shares",
         "ticker":"VTIAX",
         "assetClass":"International",
         "expenseRatio":"0.11%",
         "price":"$32.98",
         "priceChange":"-$0.28",
         "ytd":"4.75%",
         "oneyr":"10.47%",
         "fiveyr":"9.46%",
         "tenyr":"6.96%",
         "sinceInception":"5.71%"
      },
      {
         "name":"Emerging Markets Select Stock",
         "ticker":"VMMSX",
         "assetClass":"International",
         "expenseRatio":"0.85%",
         "price":"$23.54",
         "priceChange":"-$2.14",
         "ytd":"-4.83%",
         "oneyr":"4.61%",
         "fiveyr":"9.54%",
         "tenyr":"5.63%",
         "sinceInception":"3.86%"
      },
      {
         "name":"Emerging Markets Stock Index  Admiral Shares",
         "ticker":"VEMAX",
         "assetClass":"International",
         "expenseRatio":"0.14%",
         "price":"$39.58",
         "priceChange":"-$0.68",
         "ytd":"-2.63%",
         "oneyr":"5.00%",
         "fiveyr":"9.02%",
         "tenyr":"4.82%",
         "sinceInception":"5.87%"
      },
      {
         "name":"Global Minimum Volatility",
         "ticker":"VMVFX",
         "assetClass":"International",
         "expenseRatio":"0.21%",
         "price":"$14.42",
         "priceChange":"-$0.06",
         "ytd":"9.14%",
         "oneyr":"9.29%",
         "fiveyr":"7.61%",
         "tenyr":"—",
         "sinceInception":"8.49%"
      },
      {
         "name":"Energy",
         "ticker":"VGENX",
         "assetClass":"Stock - Sector",
         "expenseRatio":"0.37%",
         "price":"$38.50",
         "priceChange":"-$0.12",
         "ytd":"22.98%",
         "oneyr":"24.68%",
         "fiveyr":"-3.86%",
         "tenyr":"-1.61%",
         "sinceInception":"8.83%"
      },
      {
         "name":"Health Care",
         "ticker":"VGHCX",
         "assetClass":"Stock - Sector",
         "expenseRatio":"0.32%",
         "price":"$237.55",
         "priceChange":"-$0.54",
         "ytd":"11.85%",
         "oneyr":"8.87%",
         "fiveyr":"12.29%",
         "tenyr":"14.71%",
         "sinceInception":"15.85%"
      },
      {
         "name":"Real Estate Index  Admiral Shares",
         "ticker":"VGSLX",
         "assetClass":"Stock - Sector",
         "expenseRatio":"0.12%",
         "price":"$157.04",
         "priceChange":"-$1.43",
         "ytd":"32.97%",
         "oneyr":"31.52%",
         "fiveyr":"10.20%",
         "tenyr":"10.98%",
         "sinceInception":"10.68%"
      }
   ];
  
    funds.forEach(fund => db.funds.insert(fund))
  }
  